#!/usr/bin/env python3
"""
Dados da Série MK5 — Estudos de Caso Práticos, Métricas e Retorno Financeiro (20 livros)
Formato: slug -> (nome, titulo_obra, subtitulo, introducao, conclusao, capitulo1_explica)
Usado por dados_series_planejamento.py (merge) via gerar-livros-planejamento.py
"""

LIVROS_MK5 = {
    "MK5-01-analise-forense-de-campanhas-fracassadas": (
        "Análise Forense de Campanhas Fracassadas",
        "Análise Forense de Campanhas Fracassadas: Como dissecar um lançamento ou campanha que deu errado para aprender e não repetir o erro",
        "Como dissecar um lançamento ou campanha que deu errado para aprender e não repetir o erro",
        "Campanha que falha deixa um rastro de pistas — e a maioria das empresas enterra o assunto em vez de investigar. Este livro ensina a análise forense de campanhas fracassadas: o método de dissecar lançamentos e campanhas que deram errado para extrair as lições e não repetir o erro.",
        "Fracasso não é aprendizado automático: é matéria-prima. A análise forense transforma o erro em conhecimento aplicado — e a empresa que investiga o fracasso com método passa a errar menos e a investir melhor do que a que esquece o prejuízo.",
        "A análise forense de campanhas investiga o fracasso com método de causa e efeito, em quatro camadas: execução (o que foi feito e como), hipótese (qual premissa falhou — oferta, público, mensagem, timing), dados (o que os números mostram de fato) e processo (o que a operação poderia ter evitado) [1]. O objetivo não é achar culpado, é isolar a causa raiz que, corrigida, evita a repetição [2].\n\n**Por que importa?** Campanhas falham por padrões repetíveis — oferta fraca, público errado, mensagem confusa, pressa de lançamento. Dissecar cada fracasso acumula um banco de lições que orienta as próximas decisões e reduz o custo do erro futuro [3].\n\n**O que muda na prática:** Para cada campanha que não atingiu a meta, faça a autópsia em reunião específica: o que esperávamos, o que aconteceu, por que aconteceu e o que mudamos — registrando a lição em documento único consultado antes de cada lançamento."
    ),
    "MK5-02-modelo-financeiro-do-marketing-para-o-cfo": (
        "O Modelo Financeiro do Marketing para o CFO",
        "O Modelo Financeiro do Marketing para o CFO: Traduzindo métricas de engajamento em relatórios que o departamento financeiro compreende",
        "Traduzindo métricas de engajamento em relatórios que o departamento financeiro compreende",
        "O CFO não se impressiona com alcance: ele quer saber quanto o marketing custa, quanto retorna e em quanto tempo. Este livro ensina a construir o modelo financeiro do marketing — a ponte que traduz métricas de engajamento em relatórios de investimento, retorno e payback que o financeiro compreende e aprova.",
        "O modelo financeiro do marketing é a linguagem que garante orçamento: quando cada real investido é explicado em retorno e prazo, o marketing deixa de ser centro de custo e vira centro de investimento na visão do financeiro.",
        "O modelo financeiro do marketing organiza as métricas em três blocos que o CFO reconhece: investimento (verba de mídia, ferramentas, time e produção), retorno (receita atribuída, margem de contribuição e lucro gerado) e eficiência (CAC, LTV, ROI, payback e break-even) [1]. A construção parte do funil: cada etapa converte valor — cliques viram leads, leads viram vendas, vendas viram margem [2].\n\n**Por que importa?** O financeiro aprova orçamento com base em previsibilidade: relatórios de engajamento não respondem à pergunta dele ('quanto isso rende?'). O modelo financeiro responde com números e constrói a confiança que sustenta o investimento em marketing [3].\n\n**O que muda na prática:** Monte o mapa investimento→retorno do seu funil, calcule CAC, LTV, ROI e payback por canal, e apresente ao financeiro o relatório mensal em linguagem financeira: quanto entrou, quanto custou e quanto sobrou."
    ),
    "MK5-03-payback-e-ponto-de-equilibrio": (
        "Cálculo de Payback e Ponto de Equilíbrio (Break-Even)",
        "Cálculo de Payback e Ponto de Equilíbrio: Descobrindo exatamente em quanto tempo o dinheiro investido em marketing retorna ao caixa",
        "Descobrindo exatamente em quanto tempo o dinheiro investido em marketing retorna ao caixa",
        "Investir em marketing sem saber o payback é apostar no escuro: o dinheiro sai hoje e a dúvida é se — e quando — volta. Este livro ensina a calcular payback e ponto de equilíbrio: o tempo exato de retorno do investimento e o volume de vendas que cobre os custos, a matemática que separa investimento de gasto.",
        "Payback e break-even são os números que respondem 'vale a pena?': com eles, cada decisão de verba vira cálculo — quanto investir, quanto precisa vender e em quanto tempo o caixa se recupera. Quem domina essa matemática investe com segurança.",
        "O payback mede em quanto tempo o investimento em marketing se paga: investimento dividido pela margem de contribuição gerada por período [1]. O ponto de equilíbrio (break-even) mostra o volume de vendas necessário para cobrir custos fixos e variáveis — o mínimo abaixo do qual a operação perde dinheiro [2].\n\n**Por que importa?** O marketing que não calcula payback não sabe se cresce ou sangra: uma campanha pode gerar vendas e ainda assim destruir caixa se o retorno demorar mais que a folga financeira. Payback e break-even transformam verba em decisão matemática [3].\n\n**O que muda na prática:** Calcule a margem de contribuição por venda, o payback de cada canal (investimento ÷ margem mensal) e o break-even do negócio — e use os três números como critério de aprovação de qualquer investimento em marketing."
    ),
    "MK5-04-projecoes-de-crescimento-baseadas-em-cenarios": (
        "Projeções de Crescimento Baseadas em Cenários",
        "Projeções de Crescimento Baseadas em Cenários: Criando modelos de previsão de vendas otimistas, realistas e pessimistas para o planejamento anual",
        "Criando modelos de previsão de vendas otimistas, realistas e pessimistas para o planejamento anual",
        "Planejar o ano com uma única previsão é preparar a empresa para um futuro que não existe. Este livro ensina projeções de crescimento baseadas em cenários: modelos de previsão de vendas otimista, realista e pessimista — a base do planejamento anual que sobrevive à realidade.",
        "Cenários não são pessimismo: são preparo. Com o otimista, o realista e o pessimista definidos, a empresa sabe o que fazer em cada futuro — e o plano anual deixa de ser uma aposta única para ser um leque de respostas prontas.",
        "A projeção por cenários constrói três modelos a partir das mesmas premissas: o realista (tendência atual e desempenho histórico), o otimista (alavancas que aceleram — novos canais, campanhas, parcerias) e o pessimista (riscos que desaceleram — custo de mídia, concorrência, sazonalidade negativa) [1]. Cada cenário define premissas de conversão, ticket e volume, gerando receita, CAC e margem esperados [2].\n\n**Por que importa?** A empresa que planeja por cenário reage rápido: quando a realidade pende para o pessimista, o plano de contingência já existe; quando supera o otimista, o time já sabe onde investir o excedente [3].\n\n**O que muda na prática:** Monte a planilha de premissas (conversão, ticket, investimento), construa os três cenários do ano, defina os gatilhos que indicam qual cenário está se materializando e revise a projeção trimestralmente contra o realizado."
    ),
    "MK5-05-auditoria-de-eficiencia-de-canais-kill-or-fix": (
        "Auditoria de Eficiência de Canais (Kill or Fix)",
        "Auditoria de Eficiência de Canais: A metodologia prática para cortar os 20% piores investimentos e realocar verba nos canais lucrativos",
        "A metodologia prática para cortar os 20% piores investimentos e realocar verba nos canais lucrativos",
        "A maioria das empresas gasta em canais por hábito, não por resultado: o canal que já morreu continua recebendo verba. Este livro ensina a auditoria de eficiência de canais — a metodologia kill or fix que identifica os 20% piores investimentos e realoca a verba nos canais que realmente geram retorno.",
        "Eficiência de canal é decisão de alocação, não de volume: o mesmo orçamento rende muito mais quando sai dos canais ruins e vai para os bons. A auditoria kill or fix é a ferramenta que corta o desperdício com base em números.",
        "A auditoria de eficiência de canais mede cada canal por indicadores comparáveis: CAC, ROI, payback e margem gerada — não por volume de leads ou impressões [1]. O resultado divide os canais em três grupos: manter (retorno acima do piso), corrigir (fix — potencial não explorado, ajustar oferta ou execução) e cortar (kill — abaixo do piso sem caminho claro de recuperação) [2].\n\n**Por que importa?** A regra do Pareto se aplica à verba: geralmente 20% dos investimentos geram a maior parte do desperdício. Cortá-los e realocar libera resultado imediato sem aumentar o orçamento — o ganho mais barato que existe em marketing [3].\n\n**O que muda na prática:** Monte a tabela de canais com CAC, ROI e payback, defina o piso mínimo aceitável, classifique cada canal em manter/corrigir/cortar e realoque a verba dos cortados para os eficientes, monitorando o efeito no trimestre."
    ),
    "MK5-06-analise-de-cohort-aplicada-a-retencao": (
        "Análise de Cohort Aplicada à Retenção de Clientes",
        "Análise de Cohort Aplicada à Retenção: Acompanhando o comportamento de grupos de compradores ao longo do tempo para elevar o LTV",
        "Acompanhando o comportamento de grupos de compradores ao longo do tempo para elevar o LTV",
        "A média esconde a verdade: clientes de janeiro se comportam diferente dos de julho, e a média não mostra. Este livro ensina análise de cohort — o método de acompanhar grupos de compradores ao longo do tempo para enxergar retenção e recompra reais e elevar o LTV.",
        "Cohort é a lente que revela o comportamento verdadeiro do cliente: em vez de uma média que esconde, cada grupo mostra sua curva de retenção e recompra. Quem enxerga as curvas sabe exatamente onde o cliente perde valor e como recuperá-lo.",
        "A análise de cohort agrupa clientes por período de aquisição (mês, trimestre ou campanha) e acompanha o comportamento de cada grupo ao longo do tempo: quantos compram de novo no mês 1, no mês 2, no mês 3 [1]. A leitura das curvas revela a retenção real (grupos recentes retêm igual aos antigos?) e o efeito de mudanças — campanhas, preço, produto — sobre o valor do cliente [2].\n\n**Por que importa?** Métricas agregadas como 'ticket médio' escondem o declínio: a empresa pode ter receita estável enquanto cada nova coorte retém pior. A análise de cohort antecipa o problema do LTV e mostra onde investir em retenção [3].\n\n**O que muda na prática:** Estruture a tabela de coortes por mês de aquisição, acompanhe recompra e receita por grupo ao longo dos meses, compare as curvas entre períodos e use os achados para priorizar ações de retenção nos momentos de maior queda."
    ),
    "MK5-07-medindo-o-impacto-do-branding-a-longo-prazo": (
        "Medindo o Impacto do Branding e da Marca a Longo Prazo",
        "Medindo o Impacto do Branding e da Marca a Longo Prazo: Métricas financeiras e de percepção para avaliar o valor gerado por campanhas institucionais",
        "Métricas financeiras e de percepção para avaliar o valor gerado por campanhas institucionais",
        "Branding não aparece no relatório de vendas do mês — e por isso é o primeiro orçamento cortado. Este livro ensina a medir o impacto do branding e da marca a longo prazo: métricas de percepção e financeiras que mostram o valor das campanhas institucionais além da venda imediata.",
        "O que não se mede não se defende: sem métricas de marca, o branding vira gasto questionável. Com indicadores de percepção, busca e preço, a empresa mostra o valor das campanhas institucionais — e protege o orçamento que constrói o futuro.",
        "A medição do branding combina dois grupos de métricas: percepção (lembrança de marca, associações, sentimento, busca pela marca no Google e redes) e financeiras (preço prêmio — quanto a marca permite cobrar a mais —, elasticidade de preço, participação de mercado e contribuição para o LTV) [1]. O efeito do branding se revela no tempo: mais busca espontânea, mais indicação, mais recompra e mais tolerância a preço [2].\n\n**Por que importa?** Marca é o ativo que barateia toda a aquisição: o cliente que conhece e confia converte mais, custa menos e tolera preço maior. Medir o branding mostra que campanhas institucionais não são gasto — são investimento em margem futura [3].\n\n**O que muda na prática:** Defina as métricas de percepção do seu mercado (busca, lembrança, sentimento), meça a linha de base, acompanhe a evolução após campanhas institucionais e cruze com indicadores financeiros — preço prêmio e recompra — para mostrar o retorno da marca."
    ),
    "MK5-08-planejamento-de-margem-de-lucro-por-produto": (
        "Planejamento de Margem de Lucro por Produto/Serviço",
        "Planejamento de Margem de Lucro por Produto: Cruzando dados de marketing com a margem de contribuição de cada item do portfólio",
        "Cruzando dados de marketing com a margem de contribuição de cada item do portfólio da empresa",
        "Vender muito não é vender bem: o produto que mais vende pode ser o que menos margem dá. Este livro ensina o planejamento de margem por produto — cruzando os dados de marketing com a margem de contribuição de cada item do portfólio para alocar verba onde o lucro é real.",
        "Marketing sem visão de margem otimiza o volume errado: direciona esforço para o produto que vende e destrói o lucro. O planejamento por margem alinha aquisição, oferta e preço ao produto que realmente sustenta o negócio.",
        "O planejamento de margem por produto cruza duas dimensões: a margem de contribuição de cada item (preço menos custos variáveis — o quanto sobra por venda) e os dados de marketing (quanto custa adquirir cliente para cada produto, por canal) [1]. O cruzamento revela o lucro real por item e por canal — e expõe produtos que vendem mas não compensam [2].\n\n**Por que importa?** Decisões de marketing baseadas só em volume distorcem o portfólio: verba vai para o produto de maior venda e menor margem, enquanto o produto lucrativo definha. A visão por margem realoca esforço e protege o lucro operacional [3].\n\n**O que muda na prática:** Monte a tabela de margem de contribuição por produto, cruze com CAC e volume de venda por canal, classifique o portfólio em estrelas (vende e margem alta), vacas (margem alta, venda baixa) e armadilhas (vende, margem baixa) e direcione a verba para as duas primeiras."
    ),
    "MK5-09-sazonalidade-de-caixa-e-capital-de-giro": (
        "Análise de Sazonalidade de Caixa e Capital de Giro",
        "Análise de Sazonalidade de Caixa e Capital de Giro: Alinhando as campanhas de marketing agressivas com os meses de maior fôlego financeiro",
        "Alinhando as campanhas de marketing agressivas com os meses de maior fôlego financeiro da empresa",
        "Campanha agressiva no mês de caixa apertado é receita de crise: o marketing cresce em dezembro e quebra em janeiro. Este livro ensina a análise de sazonalidade de caixa e capital de giro — alinhando campanhas ao fôlego financeiro real da empresa para crescer sem afogar o caixa.",
        "Marketing e finanças têm que dançar a mesma música: investir quando o caixa sustenta e moderar quando ele aperta. A análise de sazonalidade alinha o calendário de campanhas ao fluxo financeiro — crescimento agressivo nos meses de folga, contenção nos de aperto.",
        "A análise de sazonalidade cruza dois calendários: o do caixa (entradas e saídas mês a mês, apontando os meses de folga e aperto) e o do marketing (campanhas, datas e investimentos planejados) [1]. O alinhamento define quando investir agressivo (meses com fôlego, após picos de receita) e quando moderar (meses de saída forte ou receita fraca) — protegendo o capital de giro [2].\n\n**Por que importa?** O maior risco do crescimento é a falta de caixa para sustentá-lo: campanha que gera demanda no mês errado obriga a empresa a descapitalizar para honrar o pedido. O alinhamento evita crescer no vermelho [3].\n\n**O que muda na prática:** Monte o fluxo de caixa mensal previsto, marque os meses de folga e aperto, ajuste o calendário de campanhas a essa curva e mantenha reserva de capital de giro para os picos de demanda planejados."
    ),
    "MK5-10-construcao-de-um-data-warehouse-simplificado": (
        "Construção de um Data Warehouse Simplificado",
        "Construção de um Data Warehouse Simplificado: Centralizando dados de vendas, anúncios e atendimento em um único local de análise",
        "Centralizando dados de vendas, anúncios e atendimento em um único local de análise",
        "Os dados estão espalhados: vendas no sistema, anúncios na plataforma, atendimento no WhatsApp — e a análise manual consome dias. Este livro ensina a construir um data warehouse simplificado: centralizar vendas, anúncios e atendimento em um único local para análise rápida e decisão com dados.",
        "Dados centralizados são o painel único da empresa: quando vendas, anúncios e atendimento vivem no mesmo lugar, a análise que levava dias leva horas e o gestor enxerga o negócio inteiro sem planilhas paralelas.",
        "Um data warehouse simplificado centraliza dados de múltiplas fontes em três etapas: extração (puxar dados de vendas, plataformas de anúncio e atendimento), padronização (unificar formatos, nomes e moedas) e carga (armazenar em um único local — planilha estruturada, banco simples ou ferramenta de BI) [1]. O essencial não é a tecnologia, é a estrutura: dados limpos, com datas e dimensões padronizadas, prontos para análise [2].\n\n**Por que importa?** Análise em dados espalhados gera decisão errada: cada área olha um número e o gestor não tem a visão única. O data warehouse simplificado dá a base para painéis, atribuição e projeções confiáveis [3].\n\n**O que muda na prática:** Liste as fontes de dados da empresa, defina o modelo mínimo (data, canal, valor, produto, cliente), automatize a coleta semanal e construa o painel único que cruza vendas, marketing e atendimento."
    ),
    "MK5-11-indicadores-preditivos-vs-indicadores-historicos": (
        "Uso de Indicadores Preditivos vs. Indicadores Históricos",
        "Uso de Indicadores Preditivos vs. Indicadores Históricos: Monitorando sinais antecipados de queda nas vendas antes que o prejuízo aconteça no caixa",
        "Monitorando sinais antecipados de queda nas vendas antes que o prejuízo aconteça no caixa",
        "Indicador histórico diz o que aconteceu; indicador preditivo diz o que vem. A empresa que só olha para trás descobre a queda quando ela já virou prejuízo. Este livro ensina a combinar indicadores preditivos e históricos — monitorando os sinais antecipados que avisam antes do dano chegar ao caixa.",
        "O valor do indicador está em antecedência: o histórico mostra o passado com precisão, mas é o preditivo que dá tempo de agir. Quem combina os dois monitora a queda em formação e corrige a rota antes do prejuízo.",
        "Indicadores históricos medem o que já aconteceu (vendas do mês, CAC realizado, conversão passada) e são essenciais para avaliar — mas só reagem ao passado [1]. Indicadores preditivos apontam o que vem: volume de leads novos, tempo de conversão no funil, sinal de demanda, comportamento de recompra e tendências de busca [2].\n\n**Por que importa?** Queda de vendas não acontece de repente: ela se anuncia antes — leads caindo, funil desacelerando, recompra diminuindo. O gestor que monitora os sinais preditivos corrige em semanas; o que espera o histórico corrige em meses, já com prejuízo [3].\n\n**O que muda na prática:** Defina os indicadores preditivos do seu funil (leads, conversão de etapa, recompra), acompanhe-os em painel semanal junto com o histórico e estabeleça os gatilhos de alerta que disparam ação antes da queda chegar ao caixa."
    ),
    "MK5-12-como-medir-o-roi-de-marketing-tradicional": (
        "Como Medir o ROI de Ações de Marketing Tradicional",
        "Como Medir o ROI de Ações de Marketing Tradicional: Métricas e artifícios (cupons, QR codes específicos, pesquisas de origem) para rastrear o offline",
        "Métricas e artifícios (cupons, QRs codes específicos, pesquisas de origem) para rastrear o offline",
        "O offline sempre foi o canal que 'não dá para medir' — até que se aprende os artifícios certos. Este livro ensina a medir o ROI de ações de marketing tradicional: cupons, QR codes específicos, pesquisas de origem e outros métodos para rastrear o que antes era invisível.",
        "Todo canal tem retorno — o problema é o rastreio. Com artifícios simples de atribuição, o marketing tradicional (panfleto, rádio, fachada, evento) sai da escuridão e entra no mesmo painel de ROI dos canais digitais.",
        "A medição do offline usa artifícios de atribuição: cupons e códigos por canal (um código para o panfleto, outro para a rádio), QR codes específicos em materiais, telefones ou WhatsApp dedicados, e pesquisa de origem no momento da compra ('como você nos conheceu?') [1]. O cruzamento desses dados mostra o retorno de cada ação tradicional com precisão suficiente para decidir [2].\n\n**Por que importa?** A desculpa de que o offline não se mede condena o canal ao preconceito: sem números, corta-se a verba do que pode estar funcionando. Com rastreio, o tradicional compete de igual para igual na alocação de orçamento [3].\n\n**O que muda na prática:** Atribua códigos e QR únicos por ação, use telefone/WhatsApp dedicado por canal, pergunte a origem na venda e monte o painel que compara o ROI do offline com o do digital mês a mês."
    ),
    "MK5-13-auditoria-de-descontos-e-promocoes-na-margem": (
        "Auditoria de Descontos e Promoções na Margem",
        "Auditoria de Descontos e Promoções na Margem: Analisando se as campanhas de liquidação realmente trazem lucro ou apenas empurram prejuízo",
        "Analisando se as campanhas de liquidação realmente trazem lucro ou apenas empurram prejuízo",
        "Desconto vende — mas vende com lucro ou empurra prejuízo? A maioria das empresas desconta sem saber o efeito na margem. Este livro ensina a auditar descontos e promoções: analisar se cada campanha de liquidação gera lucro real, considerando margem, volume adicional e efeito sobre o preço percebido.",
        "Desconto é ferramenta de caixa e de giro, não de hábito: usado sem auditoria, vira venda que prejuízo. A auditoria de promoções mostra qual desconto gera lucro incremental e qual apenas transfere a compra de amanhã para hoje — com margem menor.",
        "A auditoria de descontos analisa cada promoção em três dimensões: margem (o quanto o desconto comprime a contribuição por venda), incremento (quantas vendas são realmente adicionais — e não apenas antecipadas) e caixa (o efeito no giro e na liquidez) [1]. A análise compara o cenário com e sem desconto para isolar o efeito real [2].\n\n**Por que importa?** A promoção sem auditoria vicia o cliente em desconto e corrói a margem: no fim do ano, a empresa vendeu mais e lucrou menos. A auditoria revela o desconto que gera lucro incremental e elimina o que só antecipa venda com preço menor [3].\n\n**O que muda na prática:** Antes de toda promoção, defina a margem mínima aceitável; depois, meça o incremento real (vendas com desconto vs. linha de base) e a margem líquida — e padronize os descontos que provaram gerar lucro incremental."
    ),
    "MK5-14-relatorios-executivos-para-tomadores-de-decisao": (
        "Relatórios Executivos para Tomadores de Decisão",
        "Relatórios Executivos para Tomadores de Decisão: Como resumir semanas de trabalho de marketing em um slide de 5 minutos para os sócios",
        "Como resumir semanas de trabalho de marketing em um slide de 5 minutos para os sócios",
        "Os sócios não têm tempo para semanas de relatório — eles têm 5 minutos e uma pergunta: o resultado foi bom? Este livro ensina a produzir relatórios executivos de marketing: o resumo que condensa semanas de trabalho em um slide claro, com números e decisão, para tomadores de decisão.",
        "Relatório executivo é a arte de resumir sem perder o essencial: o gestor que apresenta em um slide o que o time fez, o que rendeu e o que decidir ganha a atenção — e o orçamento — dos sócios.",
        "O relatório executivo segue a pirâmide da comunicação: primeiro a conclusão (o resultado do período em uma frase), depois os números que sustentam (receita, margem, CAC, ROI) e por fim as recomendações (o que manter, cortar e testar) [1]. O formato ideal é curto: 1 página ou 5 slides, com os 3 a 5 indicadores que respondem 'estamos ganhando dinheiro?' [2].\n\n**Por que importa?** Tomador de decisão decide com o que entende: relatório denso perde a atenção e a decisão vira 'esperar para ver'. O relatório executivo transforma o trabalho do time em decisão rápida e informada [3].\n\n**O que muda na prática:** Estruture o relatório em conclusão-números-recomendações, limite a 1 página com os indicadores-mestre, inclua sempre a pergunta de decisão ('o que os sócios precisam decidir?') e apresente em reunião curta de 15 minutos."
    ),
    "MK5-15-gargalos-de-conversao-no-funil-oculto": (
        "Identificação de Gargalos de Conversão no Funil Oculto",
        "Identificação de Gargalos de Conversão no Funil Oculto: Encontrando onde os clientes desistem de comprar nos canais de atendimento manual",
        "Encontrando onde os clientes desistem de comprar nos canais de atendimento manual",
        "O site converte bem, mas a venda morre no atendimento: o lead chega ao WhatsApp, demora para ser respondido e desiste. Este livro ensina a identificar os gargalos de conversão no funil oculto — os pontos de desistência nos canais de atendimento manual que o painel digital não mostra.",
        "O funil oculto é onde a venda se perde em silêncio: atendimento lento, resposta sem contexto, follow-up inexistente. Quem mapeia os gargalos manuais recupera vendas que o tráfego já pagou — sem gastar mais um centavo em aquisição.",
        "O funil oculto cobre os canais de atendimento manual: WhatsApp, telefone, e-mail e balcão [1]. Os gargalos típicos: tempo de resposta alto (o lead esfria em minutos), atendimento sem contexto (repetir a história), falta de follow-up (a maioria das vendas B2B exige mais de um contato) e ausência de gestão do atendimento (quem responde, quando, com que qualidade) [2].\n\n**Por que importa?** O custo de aquisição já foi pago quando o lead chega ao atendimento: perder a venda ali é desperdiçar o investimento inteiro de mídia. Corrigir o funil oculto é a alavanca de conversão mais barata da operação [3].\n\n**O que muda na prática:** Mapeie as etapas do atendimento manual, meça o tempo de resposta e a taxa de desistência por etapa, padronize o processo (resposta rápida, contexto único, follow-up programado) e monitore o atendimento como parte do funil de conversão."
    ),
    "MK5-16-turnaround-de-empresa-em-crise-de-vendas": (
        "Estudo de Caso: A Turnaround de uma Empresa em Crise de Vendas",
        "Estudo de Caso: A Turnaround de uma Empresa em Crise de Vendas: Passo a passo prático de como reestruturar o marketing de um negócio estagnado",
        "Passo a passo prático de como reestruturar o marketing de um negócio estagnado",
        "A empresa estagnada não precisa de mais do mesmo: precisa de reestruturação. Este livro apresenta o estudo de caso completo de um turnaround — o passo a passo prático de como reestruturar o marketing de um negócio estagnado, do diagnóstico à retomada do crescimento.",
        "Turnaround é método, não milagre: a sequência de diagnosticar, parar a hemorragia, reorganizar e retomar cresce o negócio em meses. O estudo de caso mostra cada etapa aplicada a um caso real — e o que pode ser replicado em qualquer empresa estagnada.",
        "O turnaround de vendas segue uma sequência testada: diagnóstico (por que a empresa estagnou — mercado, oferta, execução ou posicionamento), estancamento (cortar o que sangra caixa e concentrar no que gera receita imediata), reorganização (reestruturar oferta, canais e mensagem) e retomada (escalar o que provou funcionar) [1]. O estudo de caso mostra cada etapa com os números antes e depois [2].\n\n**Por que importa?** Empresas estagnadas repetem o mesmo plano com a expectativa de resultado diferente — e afundam lentamente. O método de turnaround quebra o ciclo com diagnóstico honesto e sequência disciplinada de ação [3].\n\n**O que muda na prática:** Aplique a sequência no seu negócio: faça o diagnóstico com números, pare a hemorragia nas primeiras semanas, reorganize oferta e canais no trimestre e defina os marcos de retomada mensuráveis para os 6 meses seguintes."
    ),
    "MK5-17-mitigacao-do-ad-fatigue": (
        "Mitigação do Efeito da Saturação de Anúncios (Ad Fatigue)",
        "Mitigação do Efeito da Saturação de Anúncios: Identificando o momento exato em que o público cansa de ver uma campanha e como substituí-la",
        "Identificando o momento exato em que o público cansa de ver uma campanha e como substituí-la",
        "O anúncio que converteu lindamente no mês passado agora custa o dobro e converte metade: o público cansou. Este livro ensina a mitigar o efeito da saturação de anúncios (ad fatigue) — identificar o momento exato em que o público se cansa de ver a campanha e substituí-la antes que o ROI desabe.",
        "Ad fatigue é o imposto invisível da mídia paga: quanto mais o público vê o mesmo anúncio, mais caro e menos efetivo ele fica. Quem monitora os sinais de fadiga substitui o criativo no momento certo — mantendo o custo estável e a campanha viva.",
        "O ad fatigue se manifesta em sinais medíveis: queda na taxa de cliques, aumento do custo por resultado, queda na frequência de conversão e estagnação do alcance [1]. O monitoramento desses indicadores por anúncio identifica o início da fadiga antes do colapso do ROI [2].\n\n**Por que importa?** Deixar o anúncio no ar além da vida útil é queimar verba: a mesma audiência responde cada vez pior e o custo dispara. A rotação planejada de criativos mantém a campanha fresca e o ROI estável — sem depender de sorte [3].\n\n**O que muda na prática:** Monitore CTR, custo e frequência por anúncio, defina os gatilhos de fadiga (ex.: CTR caiu X% ou custo subiu X%), prepare criativos de reposição em estoque e institua a rotina de troca de criativos antes que os sinais virem prejuízo."
    ),
    "MK5-18-gestao-de-portfolio-de-ofertas-curva-abc": (
        "Gestão de Portfólio de Ofertas Baseada em Curva ABC",
        "Gestão de Portfólio de Ofertas Baseada em Curva ABC: Direcionando o esforço de marketing para os produtos que realmente trazem faturamento",
        "Direcionando o esforço de marketing para os produtos que realmente trazem faturamento",
        "Poucos produtos geram a maior parte do faturamento — e o marketing que trata todos iguais desperdiça esforço. Este livro ensina a gestão de portfólio baseada em curva ABC: classificar produtos por faturamento e margem e direcionar o esforço de marketing para os que realmente sustentam o negócio.",
        "A curva ABC mostra onde o dinheiro está: os poucos produtos que geram a maior parte da receita merecem a maior parte do esforço. Com o portfólio classificado, o marketing prioriza com critério em vez de distribuir atenção igualmente.",
        "A curva ABC classifica o portfólio pelo faturamento: itens A (os 20% que geram ~80% da receita), itens B (a faixa intermediária) e itens C (os muitos que geram pouco) [1]. A gestão cruza a classificação com a margem e define o tratamento por classe: itens A recebem o esforço principal de aquisição e retenção; itens C são revistos, agrupados ou descontinuados [2].\n\n**Por que importa?** Esforço de marketing distribuído uniformemente rende pouco: metade da verba vai para produtos que geram fração da receita. A gestão ABC concentra esforço onde o retorno é maior — e expõe o portfólio que não compensa [3].\n\n**O que muda na prática:** Monte a tabela de faturamento e margem por produto, classifique em A/B/C, defina o plano de marketing por classe (prioridade para A, otimização para B, decisão para C) e revise a classificação a cada trimestre."
    ),
    "MK5-19-orcamento-base-zero-obz-aplicado-ao-marketing": (
        "Orçamento Base Zero (OBZ) aplicado ao Marketing",
        "Orçamento Base Zero aplicado ao Marketing: Justificando cada centavo do orçamento do zero a cada novo ciclo de planejamento estratégico",
        "Justificando cada centavo do orçamento do zero a cada novo ciclo de planejamento estratégico",
        "O orçamento do ano passado vira direito adquirido — e o desperdício se perpetua. O Orçamento Base Zero (OBZ) reinicia a conta em zero a cada ciclo: cada centavo precisa ser justificado pelo retorno esperado. Este livro ensina a aplicar o OBZ ao marketing, do orçamento de mídia às ferramentas.",
        "OBZ é a auditoria preventiva do orçamento: nada entra por inércia, tudo entra por mérito. Aplicado ao marketing, ele elimina o desperdício histórico e direciona a verba para o que provou (ou promete) retorno — a cada ciclo, do zero.",
        "O Orçamento Base Zero parte do zero em cada ciclo e exige justificativa para cada centavo: cada canal, ferramenta e ação é avaliado pelo retorno esperado e pela prioridade, em vez de herdar o valor do ano anterior [1]. A aplicação no marketing divide o orçamento em pacotes de decisão — mídia, ferramentas, produção, eventos — e cada pacote é ranqueado por impacto esperado [2].\n\n**Por que importa?** O orçamento herdado carrega os erros do passado: o canal que morreu continua com verba, a ferramenta sem uso continua paga. O OBZ força a revisão anual de tudo e libera verba dos itens que não geram retorno [3].\n\n**O que muda na prática:** No próximo ciclo, monte o orçamento do zero: liste todos os pacotes de gasto, ranqueie por retorno esperado e prioridade, corte o que não justifica e invista a verba liberada nos itens de maior impacto — repetindo o exercício a cada ano."
    ),
    "MK5-20-balanco-final-do-ciclo-de-marketing": (
        "O Balanço Final do Ciclo de Marketing",
        "O Balanço Final do Ciclo de Marketing: O método definitivo para fechar o ano avaliando acertos, erros e preparando a base para o próximo planejamento",
        "O método definitivo para fechar o ano avaliando acertos, erros e preparando a base para o próximo planejamento",
        "O ano de marketing termina — e a maioria das empresas passa direto para o próximo plano sem olhar para trás. Este livro ensina o balanço final do ciclo de marketing: o método definitivo para fechar o ano avaliando acertos, erros e resultados, e transformar o aprendizado na base do próximo planejamento.",
        "O balanço final transforma um ano de experiência em um ano de sabedoria: o que funcionou é replicado, o que falhou é evitado e o planejamento seguinte nasce com dados, não com achismos. Fechar o ciclo com método é o que separa o time que evolui do que repete.",
        "O balanço final do ciclo segue uma estrutura: resultados (o que foi entregue contra as metas — receita, CAC, ROI, marcos), acertos (o que funcionou e deve ser mantido ou ampliado), erros (o que falhou, por que e como evitar) e aprendizados (as lições que mudam a operação) [1]. A revisão olha também para o mercado: o que mudou no cenário, na concorrência e no cliente [2].\n\n**Por que importa?** Planejamento sem balanço repete os erros do ano: a empresa recomeça do zero sem o conhecimento acumulado. O balanço fecha o ciclo e abre o próximo com base sólida — cada ano começa mais inteligente que o anterior [3].\n\n**O que muda na prática:** Agende o balanço anual em rito dedicado, avalie resultados contra metas com números, documente acertos, erros e aprendizados, e use o documento como primeira entrada do planejamento do ano seguinte."
    ),
}
