#!/usr/bin/env python3
"""
Dados da Série MK4 — Operações, Processos e Gestão de Equipes de Marketing (20 livros)
Formato: slug -> (nome, titulo_obra, subtitulo, introducao, conclusao, capitulo1_explica)
Usado por dados_series_planejamento.py (merge) via gerar-livros-planejamento.py
"""

LIVROS_MK4 = {
    "MK4-01-estruturacao-do-departamento-de-marketing-moderno": (
        "Estruturação do Departamento de Marketing Moderno",
        "Estruturação do Departamento de Marketing Moderno: Organizando papéis e responsabilidades em equipes enxutas e orientadas a resultados",
        "Organizando papéis e responsabilidades em equipes enxutas e orientadas a resultados",
        "O departamento de marketing moderno não é um aglomerado de funções: é uma operação desenhada com papéis claros, responsabilidades definidas e foco em resultado. Este livro ensina a estruturar o departamento — do organograma à rotina — para equipes enxutas que entregam com consistência.",
        "Estrutura não é burocracia: é previsibilidade. Com papéis claros, o time sabe quem faz o quê, as entregas não dependem de herói e a operação escala sem contratar a cada projeto. O departamento bem estruturado é a fundação de todas as outras práticas de marketing.",
        "A estruturação do departamento de marketing moderno define papéis por resultado, não por título: quem responde por aquisição, por conversão, por conteúdo, por dados e por relacionamento [1]. Em equipes enxutas, uma pessoa acumula funções — e o desenho organizacional precisa deixar claro quais combinações fazem sentido e quais criam gargalo [2].\n\n**Por que importa?** Sem estrutura, o marketing funciona na base do voluntariado: cada um faz um pouco de tudo, nada é dono de resultado e o retrabalho consome a energia do time. A estruturação alinha responsabilidades, prioridades e métricas de cada papel [3].\n\n**O que muda na prática:** Liste as funções de marketing da empresa, agrupe por resultado (não por tarefa), atribua um dono para cada resultado-chave e defina as métricas de sucesso de cada papel antes de contratar ou delegar."
    ),
    "MK4-02-metodologias-ageis-no-marketing": (
        "Implementação de Metodologias Ágeis no Marketing (Scrum/Kanban)",
        "Implementação de Metodologias Ágeis no Marketing: Como gerenciar demandas diárias, sprints e entregas sem sobrecarregar o time",
        "Como gerenciar demandas diárias, sprints e entregas sem sobrecarregar o time",
        "O marketing vive de demandas urgentes e prazos apertados — e o caos vira rotina quando não há método. Este livro ensina a implementar metodologias ágeis no marketing: Scrum para projetos, Kanban para o fluxo contínuo, e a gestão de sprints que entrega sem sobrecarregar o time.",
        "Ágil no marketing não é moda: é a forma de transformar o caos de demandas em fluxo previsível. Com sprints e quadro visual, o time prioriza, entrega e mede — e o gestor enxerga a capacidade real antes de aceitar a próxima demanda.",
        "As metodologias ágeis aplicadas ao marketing se dividem em duas: Scrum (ciclos curtos de trabalho — sprints — com objetivo definido e revisão ao final) e Kanban (fluxo contínuo de tarefas com limite de trabalho em andamento) [1]. A escolha depende do tipo de demanda: projetos com início e fim usam Scrum; operação contínua de conteúdo e mídia usa Kanban [2].\n\n**Por que importa?** A sobrecarga do time de marketing é a causa oculta de atrasos e erros: quando tudo é urgente, nada termina bem. A gestão ágil expõe a capacidade real, prioriza pelo impacto e protege o time de demandas impossíveis [3].\n\n**O que muda na prática:** Comece com um quadro Kanban simples (a fazer, fazendo, feito), limite o trabalho em andamento, defina sprints de 1 a 2 semanas para projetos e faça a revisão semanal de entregas e prioridades."
    ),
    "MK4-03-criacao-de-sops": (
        "Criação de SOPs (Procedimentos Operacionais Padrão)",
        "Criação de SOPs: Documentando cada processo de marketing para garantir qualidade e independência de pessoas",
        "Documentando cada processo de marketing para garantir qualidade e independência de pessoas",
        "Quando a pessoa que sabe fazer sai de férias, o processo para — ou sai errado. Este livro ensina a criar SOPs (Standard Operating Procedures) para o marketing: documentar cada processo recorrente com passos claros, responsáveis e critérios de qualidade, garantindo consistência e independência de pessoas.",
        "SOP é o manual que garante que o padrão de qualidade não dependa de quem executa: o processo documentado roda com qualquer pessoa, treina rápido e evolui com o aprendizado do time. É o ativo que transforma conhecimento individual em patrimônio da empresa.",
        "Um SOP documenta um processo recorrente em quatro partes: objetivo (o que o processo entrega), pré-requisitos (o que é necessário para começar), passos (o passo a passo executável, na ordem) e critérios de qualidade (o que define que foi bem feito) [1]. Os processos prioritários para documentar são os de maior risco e frequência: publicação de conteúdo, gestão de campanhas, atendimento, aprovação de materiais e relatórios [2].\n\n**Por que importa?** A dependência de pessoas é o risco silencioso do marketing: quando o conhecimento vive só na cabeça de alguém, férias, desligamento e crescimento quebram a operação. SOPs garantem qualidade estável, onboarding rápido e melhoria contínua do processo [3].\n\n**O que muda na prática:** Liste os processos recorrentes do marketing, priorize os de maior frequência e risco, documente cada um no formato objetivo-pré-requisitos-passos-qualidade e revise os SOPs sempre que o processo melhorar."
    ),
    "MK4-04-selecao-e-integracao-de-ferramentas-martech": (
        "Seleção e Integração de Ferramentas (Stack de MarTech)",
        "Seleção e Integração de Ferramentas: Escolhendo o CRM, e-mail, automação e BI ideais para o tamanho da empresa",
        "Escolhendo o CRM, ferramentas de e-mail, automação e BI ideais para o tamanho da empresa",
        "Ferramenta demais vira caos e custo; ferramenta de menos vira trabalho manual. Este livro ensina a selecionar e integrar a stack de MarTech — CRM, e-mail, automação e BI — de acordo com o tamanho da empresa, evitando o desperdício de licenças e o atrito entre sistemas.",
        "A stack certa é a que se integra e atende o processo, não a que tem mais funcionalidades. Com poucas ferramentas bem escolhidas e conectadas, o time automatiza o essencial, mede tudo e escala sem trocar de sistema a cada ano.",
        "A seleção da stack de MarTech começa pelo processo, não pela ferramenta: mapear o que o time precisa executar (gerar leads, nutrir, vender, medir) e só então avaliar soluções [1]. Os pilares da stack típica são: CRM (fonte da verdade do cliente), automação de e-mail (nutrição), plataforma de mídia (gestão de campanhas) e BI (análise e relatórios) [2].\n\n**Por que importa?** O erro mais comum é comprar ferramentas por impulso e nunca integrá-las: dados duplicados, trabalho manual de sincronização e custo invisível de licenças. Uma stack integrada reduz retrabalho e dá visão única do funil [3].\n\n**O que muda na prática:** Liste as ferramentas atuais e o custo de cada uma, mapeie onde os dados se perdem entre elas, escolha um CRM como fonte da verdade e integre as demais ferramentas a ele — cortando as licenças que não se conectam ao processo."
    ),
    "MK4-05-gestao-de-terceirizados-e-agencias-parceiras": (
        "Gestão de Terceirizados e Agências Parceiras",
        "Gestão de Terceirizados e Agências Parceiras: Como cobrar prazos, qualidade e ROI de prestadores de serviços externos",
        "Como cobrar prazos, qualidade e ROI de prestadores de serviços externos",
        "Agencia boa não dispensa gestão: ela entrega o que se cobra — e se não houver cobrança clara, entrega o que quiser. Este livro ensina a gerir terceirizados e agências parceiras: contratos claros, escopo definido, prazos cobrados, qualidade avaliada e ROI medido.",
        "Terceirização bem gerida é alavanca; mal gerida é gasto sem retorno. Com expectativas, entregas e métricas definidas por escrito, a parceria produz resultado mensurável — e a cobrança de prazos e qualidade deixa de ser pessoal para ser contratual.",
        "A gestão de agências e terceirizados começa no contrato: escopo detalhado (o que será entregue), prazos por etapa, critérios de aprovação e métricas de desempenho [1]. A rotina de gestão inclui reuniões regulares de acompanhamento, revisão das entregas contra o escopo e o rastreio do ROI do serviço contratado [2].\n\n**Por que importa?** Sem escopo claro, o fornecedor entrega o mínimo e cobra pelo máximo; sem métricas, a empresa não sabe se a parceria traz retorno. A gestão formal transforma a relação em parceria de resultado — e facilita a troca quando o desempenho não atende [3].\n\n**O que muda na prática:** Formalize escopo, prazos e métricas no contrato ou proposta, defina o ritmo de acompanhamento, revise cada entrega contra o combinado e mensure o ROI do serviço para decidir continuar, ajustar ou trocar o parceiro."
    ),
    "MK4-06-gestao-de-projetos-de-marketing-de-longo-prazo": (
        "Gestão de Projetos de Marketing de Longo Prazo",
        "Gestão de Projetos de Marketing de Longo Prazo: Acompanhando cronogramas complexos de lançamento de produtos ou campanhas institucionais",
        "Acompanhando cronogramas complexos de lançamento de produtos ou campanhas institucionais",
        "Projetos longos morrem por falta de método: começam com entusiasmo e se perdem entre datas, áreas e prioridades. Este livro ensina gestão de projetos de marketing de longo prazo — cronogramas complexos de lançamentos e campanhas institucionais — com fases, marcos, responsáveis e acompanhamento que mantém o projeto vivo até o fim.",
        "Projeto longo exige estrutura de médio prazo: sem fases e marcos, o time perde o rumo e o escopo cresce sem controle. A gestão por marcos transforma um cronograma assustador em uma sequência de entregas verificáveis.",
        "A gestão de projetos de longo prazo organiza o trabalho em fases com marcos verificáveis: descoberta, planejamento, produção, revisão e lançamento [1]. Cada fase tem entregas claras, responsáveis e critérios de aprovação — e o cronograma é revisado em ritos regulares que identificam atrasos antes que virem crise [2].\n\n**Por que importa?** Lançamentos complexos envolvem produto, marketing, vendas e operação ao mesmo tempo: sem gestão, cada área trabalha no próprio ritmo e o dia do lançamento vira caos. A gestão por marcos alinha todos ao mesmo cronograma [3].\n\n**O que muda na prática:** Divida o projeto em fases com marcos, atribua responsáveis por entrega, defina os ritos de acompanhamento (semanal para execução, quinzenal para riscos) e mantenha um documento único com cronograma, status e decisões."
    ),
    "MK4-07-cultura-de-testes-ab": (
        "Cultura de Testes A/B na Operação Diária",
        "Cultura de Testes A/B na Operação Diária: Estabelecendo o hábito de testar criativos, copies e ofertas antes de escalar verba",
        "Estabelecendo o hábito de testar criativos, copies e ofertas antes de escalar verba",
        "Escalar verba sem testar é apostar com o dinheiro da empresa. Este livro ensina a implantar a cultura de testes A/B na operação diária do marketing: o hábito de testar criativos, copies e ofertas antes de escalar, com método estatístico simples e decisão baseada em dados.",
        "Testar antes de escalar é o que separa o marketing que aprende do marketing que aposta: cada teste gera conhecimento acumulado que reduz o risco de todas as decisões futuras. A cultura de testes transforma a operação em laboratório contínuo.",
        "A cultura de testes A/B estabelece o ciclo: hipótese (o que acredito que funciona melhor e por quê), teste (variante contra controle, com volume suficiente), leitura (resultado com significância mínima) e aplicação (o vencedor entra em produção) [1]. Os elementos mais testados no marketing são criativos, copies, ofertas, headlines, CTAs e páginas [2].\n\n**Por que importa?** Escalar uma ideia não testada multiplica o erro junto com o acerto: se a oferta converte mal, mais verba significa mais prejuízo. O teste sistemático identifica o vencedor com um investimento pequeno e só então a verba cresce com segurança [3].\n\n**O que muda na prática:** Comece com os elementos de maior impacto (oferta e criativo), defina o volume mínimo por teste, registre hipóteses e resultados em um documento único e crie a regra: nenhuma verba escala sem teste aprovado."
    ),
    "MK4-08-orcamento-e-controle-de-custos-de-software": (
        "Orçamento e Controle de Custos de Ferramentas de Software",
        "Orçamento e Controle de Custos de Ferramentas de Software: Auditando assinaturas de SaaS para evitar desperdício de tecnologia",
        "Auditando assinaturas de SaaS para evitar desperdício de tecnologia na empresa",
        "Assinaturas de software são o maior vazamento silencioso de custo do marketing: licenças esquecidas, planos superdimensionados e ferramentas duplicadas somam milhares por ano. Este livro ensina a auditar a stack de SaaS, cortar desperdício e controlar o orçamento de tecnologia com método.",
        "Controle de software não é economizar por economizar: é garantir que cada real de tecnologia gere retorno. A auditoria periódica de assinaturas libera verba para o que realmente cresce a operação — e impede o acúmulo de ferramentas que ninguém usa.",
        "A auditoria de SaaS mapeia toda a stack em uma planilha: ferramenta, plano, custo mensal/anual, usuários e uso real [1]. O processo classifica cada assinatura em: essencial (sustenta o processo), subutilizada (pode reduzir plano ou usuários) e órfã (ninguém usa — cancelar) [2].\n\n**Por que importa?** O custo de software cresce por inércia: cada contratação adiciona uma assinatura e raramente cancela a anterior. Sem auditoria, a empresa paga por duplicidade, planos altos e licenças ociosas — dinheiro que sai do caixa sem gerar resultado [3].\n\n**O que muda na prática:** Levante todas as assinaturas e o custo total, meça o uso real de cada uma, cancele ou reduza as subutilizadas e defina a política de aquisição: nova ferramenta só entra com dono, objetivo e revisão anual."
    ),
    "MK4-09-gestao-do-conhecimento-e-onboarding": (
        "Gestão do Conhecimento e Onboarding de Novos Colaboradores",
        "Gestão do Conhecimento e Onboarding de Novos Colaboradores: Treinando rapidamente novos membros do time de marketing com materiais centralizados",
        "Treinando rapidamente novos membros do time de marketing com materiais centralizados",
        "Onboarding bom é a diferença entre o colaborador que produz em semanas e o que leva meses para engrenar. Este livro ensina gestão do conhecimento e onboarding no marketing: materiais centralizados, trilhas de treinamento e a rotina que transforma o conhecimento da empresa em base acessível a todos.",
        "Conhecimento centralizado é a infraestrutura do time: com documentação, processos e exemplos em um lugar só, o novo colaborador aprende rápido, o veterano não repete explicação e a operação não trava quando alguém sai.",
        "A gestão do conhecimento organiza o saber da empresa em três camadas: documentos (manuais, SOPs, guias), processos (fluxos e responsáveis) e exemplos (materiais de referência, cases e aprendizados) — tudo centralizado e versionado [1]. O onboarding estrutura a entrada do novo colaborador em trilha: contexto do negócio, ferramentas, processos e primeiras entregas supervisionadas [2].\n\n**Por que importa?** O custo de onboardar mal é invisível: semanas de baixa produtividade, erros evitáveis e dependência dos colegas para perguntas básicas. Com materiais centralizados, o novo colaborador chega orientado e o time inteiro opera com referência comum [3].\n\n**O que muda na prática:** Centralize os materiais do time em um único local (wiki, drive ou base), documente os processos essenciais como SOPs, monte a trilha de onboarding com contexto-ferramentas-processos e designe um padrinho para as primeiras semanas."
    ),
    "MK4-10-planilhas-e-dashboards-de-controle-interno": (
        "Criação de Planilhas e Dashboards de Controle Interno",
        "Criação de Planilhas e Dashboards de Controle Interno: Desenvolvendo painéis operacionais simples em Excel ou Google Sheets para o dia a dia",
        "Desenvolvendo painéis operacionais simples em Excel ou Google Sheets para o dia a dia",
        "Ferramenta cara não resolve controle: o painel simples e bem desenhado resolve. Este livro ensina a criar planilhas e dashboards de controle interno no Excel ou Google Sheets — painéis operacionais que acompanham campanhas, orçamento, prazos e resultados no dia a dia.",
        "O dashboard de controle interno é o painel do avião do marketing: sem ele, o gestor voa no escuro. Planilhas bem estruturadas dão visibilidade instantânea de verba, entregas e resultados — e são o primeiro passo antes de qualquer ferramenta de BI.",
        "Um dashboard operacional eficiente tem três princípios: foco (poucos indicadores que orientam decisão), atualização simples (dados que entram com poucos cliques) e leitura rápida (visual que mostra tendência e alerta de imediato) [1]. As planilhas essenciais do marketing são: orçamento e execução, cronograma de entregas, funil de leads e resultados por canal [2].\n\n**Por que importa?** Sem controle interno, a gestão é reativa: o gestor descobre o estouro de orçamento ou o atraso de entrega tarde demais. O painel atualizado dá visibilidade diária e transforma o acompanhamento de tarefa burocrática em decisão rápida [3].\n\n**O que muda na prática:** Escolha as 5 métricas que o gestor precisa ver toda semana, monte a planilha-mestre com entrada simples e atualização automatizada por fórmulas, e crie a rotina de revisão semanal do painel em reunião curta."
    ),
    "MK4-11-alinhamento-com-diretoria-e-financeiro": (
        "Alinhamento de Expectativas com a Diretoria e o Financeiro",
        "Alinhamento de Expectativas com a Diretoria e o Financeiro: Falando a linguagem dos números (lucro, margem, payback) nas reuniões de diretoria",
        "Falando a linguagem dos números (lucro, margem, payback) nas reuniões de diretoria",
        "O marketing fala de cliques e curtidas; a diretoria fala de lucro e payback. Este livro ensina a alinhar expectativas com a diretoria e o financeiro: traduzir as ações de marketing para a linguagem dos números — lucro, margem, payback — e construir a confiança que garante orçamento e apoio.",
        "Quem fala a língua do financeiro ganha a sala de reunião: quando o marketing apresenta resultados em margem e retorno, a diretoria enxerga investimento, não gasto. O alinhamento de expectativas transforma a relação entre as áreas de confronto em parceria.",
        "O alinhamento com a diretoria e o financeiro começa pela tradução: cada ação de marketing deve ser apresentada em termos de investimento, retorno e prazo — quanto foi investido, quanto retornou e em quanto tempo o payback se completa [1]. As métricas que o financeiro quer ver são margem de contribuição, CAC, LTV, payback e ROI por canal [2].\n\n**Por que importa?** Quando o marketing fala de impressões, o financeiro não consegue avaliar — e a resposta padrão é cortar verba. Quando o marketing apresenta números de retorno, o orçamento deixa de ser negociação e vira decisão de investimento com critério [3].\n\n**O que muda na prática:** Prepare o relatório mensal em linguagem financeira (investimento, retorno, margem, payback), combine com o financeiro as métricas padrão e leve para a reunião de diretoria o número que interessa: o retorno de cada real investido."
    ),
    "MK4-12-gestao-de-prazos-sob-pressao": (
        "Gestão de Prazos sob Pressão em Lançamentos",
        "Gestão de Prazos sob Pressão em Lançamentos: Como manter a qualidade das entregas em momentos de pico de demandas comerciais",
        "Como manter a qualidade das entregas em momentos de pico de demandas comerciais",
        "Lançamento é o momento em que tudo acelera: prazos curtos, demandas cruzadas e a pressão por qualidade ao mesmo tempo. Este livro ensina gestão de prazos sob pressão — como manter a qualidade das entregas nos picos de demanda, priorizando, comunicando e protegendo o essencial.",
        "Pressão não é desculpa para entregar mal: é o teste do processo. Com priorização clara, comunicação de riscos e corte cirúrgico de escopo, o time entrega o essencial com qualidade mesmo no pico — e o lançamento não vira improviso.",
        "A gestão de prazos sob pressão começa antes da pressão: o lançamento exige um plano com prioridades definidas (o que é inegociável, o que pode cair) e capacidade real do time mapeada [1]. No pico, a prática é: renegociar o escopo (não o prazo), comunicar riscos cedo e proteger o time de demandas paralelas [2].\n\n**Por que importa?** O erro clássico do lançamento é aceitar tudo e entregar tudo pela metade: o dia do lançamento chega com peças incompletas e qualidade duvidosa. Priorizar o essencial e comunicar o corte com antecedência preserva o resultado — e a reputação da equipe [3].\n\n**O que muda na prática:** Para cada lançamento, defina o escopo mínimo viável, mapeie a capacidade do time, crie o plano de riscos com gatilhos de corte e comunique qualquer risco de prazo no momento em que ele aparece, não no dia da entrega."
    ),
    "MK4-13-auditoria-de-conformidade-legal-lgpd": (
        "Auditoria de Conformidade Legal (LGPD e Direitos Autorais)",
        "Auditoria de Conformidade Legal: Garantindo que imagens, dados de clientes e campanhas estejam dentro da lei",
        "Garantindo que imagens, dados de clientes e campanhas estejam dentro da lei",
        "Uma imagem copiada, uma lista de e-mails sem consentimento, um dado de cliente tratado errado: multas e danos de reputação começam em detalhes. Este livro ensina a auditar a conformidade legal do marketing — LGPD e direitos autorais — para que as campanhas operem dentro da lei.",
        "Conformidade não é gasto: é proteção. A empresa que audita dados, imagens e campanhas evita multas, processos e crises — e ainda constrói confiança com clientes que valorizam privacidade e originalidade.",
        "A auditoria de conformidade cobre duas frentes: LGPD (proteção de dados) e direitos autorais (uso de conteúdo). Na LGPD, o essencial é: base legal para cada tratamento de dado, consentimento documentado para e-mail e dados sensíveis, e transparência sobre o uso [1]. Em direitos autorais: usar apenas imagens e músicas licenciadas, respeitar marcas de terceiros e creditar fontes [2].\n\n**Por que importa?** A LGPD prevê multas expressivas e o uso indevido de imagem gera processos e crises de reputação que custam muito mais que a licença. A auditoria periódica reduz o risco e documenta a boa-fé da empresa [3].\n\n**O que muda na prática:** Mapeie onde os dados de clientes são coletados e tratados, verifique a base legal de cada lista e formulário, audite imagens e músicas usadas nos materiais e crie o checklist de conformidade para toda campanha antes do lançamento."
    ),
    "MK4-14-capacitacao-continua-da-equipe-em-ia": (
        "Capacitação Contínua da Equipe em Ferramentas de IA",
        "Capacitação Contínua da Equipe em Ferramentas de IA: Criando um plano interno para treinar o time nas novas tecnologias do mercado",
        "Criando um plano interno para treinar o time nas novas tecnologias do mercado",
        "A IA mudou o marketing — e o time que não é treinado fica para trás enquanto o concorrente escala. Este livro ensina a criar um plano interno de capacitação contínua em ferramentas de IA: trilhas por função, prática orientada e a rotina que transforma a equipe em usuária avançada das novas tecnologias.",
        "Capacitar em IA não é oferecer um curso: é criar o hábito de usar as ferramentas no trabalho real. O time treinado produz mais, testa mais e se torna o diferencial competitivo da empresa em um mercado que muda a cada trimestre.",
        "O plano de capacitação em IA segue uma trilha por função: todos aprendem o básico (o que as ferramentas fazem e os limites de uso), e cada função aprofunda no que usa no dia a dia — o redator em geração de texto, o analista em dados e automação, o gestor em estratégia apoiada por IA [1]. A prática orientada é o coração do plano: aprender fazendo, com exemplos reais do trabalho e revisão dos resultados [2].\n\n**Por que importa?** A IA comprime o tempo de produção de conteúdo, análise e campanhas: o time capacitado entrega em horas o que levava dias. A capacitação contínua também reduz o risco de uso errado — dados sensíveis, conteúdo sem revisão — que treinamento e política previnem [3].\n\n**O que muda na prática:** Avalie o nível atual do time, defina a trilha por função com foco no trabalho real, reserve tempo semanal de prática e crie o repositório de exemplos e prompts aprovados que a equipe reutiliza."
    ),
    "MK4-15-gestao-de-conflitos-entre-criatividade-e-processo": (
        "Gestão de Conflitos entre Criatividade e Processo",
        "Gestão de Conflitos entre Criatividade e Processo: Equilibrando a liberdade criativa dos designers e redatores com o rigor dos prazos e metas",
        "Equilibrando a liberdade criativa dos designers/redatores com o rigor dos prazos e metas",
        "Criativos reclamam de burocracia; gestores reclamam de atraso. Este livro ensina a gestão de conflitos entre criatividade e processo: equilibrar a liberdade criativa de designers e redatores com o rigor de prazos e metas, sem matar a criatividade nem abandonar a operação.",
        "O conflito entre criatividade e processo é falso: o processo existe para proteger a criatividade, e a criatividade precisa de limites para florescer. Quem equilibra os dois constrói um time que inova dentro do prazo.",
        "O conflito entre criatividade e processo nasce de dois medos: o criativo teme que o processo mate a ideia; o gestor teme que a criatividade atrase a entrega [1]. A gestão do conflito passa por definir juntos o que é inegociável (prazo e objetivo) e o que é espaço de liberdade (como chegar lá) — criatividade no caminho, processo na fronteira [2].\n\n**Por que importa?** Times onde o processo vence perdem a inovação; times onde a criatividade vence perdem a consistência. O equilíbrio produz entregas que são boas E no prazo — e reduz o desgaste emocional que gera rotatividade [3].\n\n**O que muda na prática:** Defina com o time o que é inegociável em cada projeto, dê autonomia criativa dentro do escopo, crie o rito de alinhamento onde criativo e gestor revisam juntos e celebre as entregas que equilibram qualidade e pontualidade."
    ),
    "MK4-16-controle-de-versionamento-de-pecas": (
        "Controle de Versionamento de Peças de Marketing",
        "Controle de Versionamento de Peças de Marketing: Organizando arquivos de design, vídeos e textos para evitar o uso de materiais desatualizados",
        "Organizando arquivos de design, vídeos e textos para evitar o uso de materiais desatualizados",
        "O logotipo antigo publicado na campanha, o anúncio com preço errado, o vídeo desatualizado no ar: erros de versão custam caro e acontecem quando os arquivos não são organizados. Este livro ensina controle de versionamento de peças de marketing — estrutura de pastas, nomenclatura e aprovação que impedem o uso de material desatualizado.",
        "Versionamento não é organização por capricho: é controle de risco. Com estrutura clara de arquivos e regras de aprovação, o time sempre publica a versão correta — e o caos de 'v1 final mesmo' acaba.",
        "O controle de versionamento organiza os arquivos em três camadas: estrutura de pastas por projeto e tipo (design, vídeo, texto, campanha), nomenclatura padronizada com versão e data (logo-v3-final-2026) e fluxo de aprovação que marca a versão aprovada como canônica [1]. A regra de ouro: apenas a versão aprovada pode ser publicada, e apenas em um local definido [2].\n\n**Por que importa?** O erro de versão é silencioso: ninguém percebe até o material errado estar no ar, em produção ou nas mãos do cliente. O dano à marca e o retrabalho custam muito mais que a disciplina de organização [3].\n\n**O que muda na prática:** Defina a estrutura de pastas padrão, adote a nomenclatura com versão e data, marque a versão aprovada de cada peça e centralize os arquivos em um único local de referência para o time."
    ),
    "MK4-17-planejamento-de-contingencia-para-falhas-de-tecnologia": (
        "Planejamento de Contingência para Falhas de Tecnologia",
        "Planejamento de Contingência para Falhas de Tecnologia: O que fazer quando o site cai, o servidor de e-mail para ou o gerenciador de anúncios bloqueia",
        "O que fazer quando o site cai, o servidor de e-mail para ou o gerenciador de anúncios bloqueia",
        "O site cai, o e-mail não dispara, a conta de anúncios é bloqueada: o marketing para — e a reação improvisada piora tudo. Este livro ensina a criar planos de contingência para falhas de tecnologia: o que fazer, quem aciona, como comunicar e como retomar cada cenário crítico.",
        "Falha de tecnologia é questão de quando, não de se: a resiliência do marketing depende do plano de contingência, não da sorte. Com procedimentos definidos, o time reage em minutos, comunica com clareza e retoma a operação com dano mínimo.",
        "O plano de contingência cobre os cenários críticos da operação: site fora do ar, falha no envio de e-mails, bloqueio de conta de anúncios, perda de dados e indisponibilidade de ferramentas [1]. Para cada cenário, o plano define: gatilho (como detectar), responsáveis (quem aciona e quem resolve), comunicação (como informar clientes e time) e retomada (como voltar a operar) [2].\n\n**Por que importa?** O custo da falha é proporcional ao tempo de resposta: uma hora sem site perde vendas; um bloqueio não tratado perde o aprendizado de anúncios e a presença digital. O plano reduz o tempo de reação de horas para minutos [3].\n\n**O que muda na prática:** Liste os cenários críticos da sua operação, defina responsáveis e passos de resposta para cada um, crie os modelos de comunicação de crise e teste o plano com um simulado por semestre."
    ),
    "MK4-18-avaliacao-de-desempenho-de-colaboradores": (
        "Avaliação de Desempenho de Colaboradores de Marketing",
        "Avaliação de Desempenho de Colaboradores de Marketing: Métricas justas para medir a produtividade e o impacto de cada profissional no negócio",
        "Métricas justas para medir a produtividade e o impacto de cada profissional no negócio",
        "Como medir o impacto de um designer, de um analista ou de um redator sem cair no subjetivismo? Este livro ensina a avaliar o desempenho de colaboradores de marketing: métricas justas por função, alinhadas ao resultado do negócio, que orientam desenvolvimento e reconhecimento.",
        "Avaliação justa é a base do time de alta performance: quando cada profissional sabe pelo que é medido e como evolui, o esforço se concentra no que gera resultado — e o reconhecimento deixa de ser favoritismo para ser mérito.",
        "A avaliação de desempenho no marketing combina dois tipos de métrica: as de resultado (indicadores do negócio que o papel influencia — CAC, conversão, entregas no prazo) e as de comportamento (qualidade, colaboração, aprendizado) [1]. O segredo é definir métricas justas por função: o redator não é medido pela conversão final sozinho, e sim pelas entregas e pelo impacto das suas peças [2].\n\n**Por que importa?** Avaliar por métricas erradas gera injustiça e desmotivação: medir todos pelos mesmos indicadores ignora que cada papel contribui de forma diferente. A avaliação por função alinha esforço individual com resultado do time [3].\n\n**O que muda na prática:** Defina as métricas de resultado e comportamento por função, combine metas com cada colaborador, faça a avaliação em rito regular (trimestral) e use os resultados para plano de desenvolvimento, não apenas para cobrança."
    ),
    "MK4-19-gestao-de-propriedade-intelectual": (
        "Gestão de Propriedade Intelectual da Marca",
        "Gestão de Propriedade Intelectual da Marca: Protegendo marcas, patentes, domínios e criativos contra cópias indevidas de concorrentes",
        "Protegendo marcas, patentes, domínios e criativos contra cópias indevidas de concorrentes",
        "A marca que você construiu pode ser copiada, o domínio pode ser tomado, o criativo pode ser pirateado — se a propriedade intelectual não for gerida. Este livro ensina a proteger a marca: registro, monitoramento e ação contra cópias de concorrentes em marcas, patentes, domínios e criativos.",
        "Propriedade intelectual é um ativo como qualquer outro: sem proteção, o valor construído pode ser diluído ou roubado. A gestão ativa de marcas, domínios e criativos blinda o patrimônio e dá base legal para agir contra a cópia.",
        "A gestão de propriedade intelectual cobre os ativos intangíveis da empresa: registro de marca (o nome e o símbolo que identificam o negócio, com direito de exclusividade), domínios e redes sociais (os endereços digitais da marca), e criativos (peças, textos e imagens protegidos por direitos autorais) [1]. O monitoramento identifica o uso indevido — cópia de marca, site falso, perfil clonado — e a resposta vai da notificação à ação legal [2].\n\n**Por que importa?** Sem registro, a marca pode ser apropriada por outro; sem monitoramento, a cópia se espalha e a empresa perde clientes e reputação. A proteção custa uma fração do dano de não ter [3].\n\n**O que muda na prática:** Registre a marca no INPI, garanta os domínios e perfis principais, documente a titularidade dos criativos e crie a rotina de monitoramento de uso indevido com procedimento de notificação."
    ),
    "MK4-20-ciclo-de-melhoria-continua-pdca": (
        "O Ciclo de Melhoria Contínua (PDCA) no Marketing",
        "O Ciclo de Melhoria Contínua no Marketing: Implantando a cultura de planejar, fazer, checar e agir em todos os processos da área",
        "Implantando a cultura de planejar, fazer, checar e agir em todos os processos da área",
        "A operação de marketing que repete os mesmos processos sem questionar nunca melhora. Este livro ensina a implantar o ciclo de melhoria contínua (PDCA) no marketing: planejar, fazer, checar e agir aplicado a campanhas, processos e times — a cultura que transforma a área em um sistema que aprende.",
        "Melhoria contínua é a diferença entre o time que repete os erros e o time que evolui: cada ciclo PDCA gera aprendizado aplicado. Quem institui a rotina de planejar, fazer, checar e agir acumula vantagem competitiva que nenhum concorrente copia da noite para o dia.",
        "O ciclo PDCA aplicado ao marketing tem quatro etapas: Planejar (definir o problema, a meta e o plano de ação), Fazer (executar o plano em escala controlada), Checar (medir os resultados contra a meta) e Agir (padronizar o que funcionou e corrigir o que não funcionou) [1]. A aplicação vai além de campanhas: vale para processos internos, atendimento, conteúdo e gestão do time [2].\n\n**Por que importa?** Sem o ciclo, a operação melhora por acaso: o que funcionou não é documentado e o que falhou se repete. Com o PDCA instituído, cada atividade vira fonte de aprendizado e a área inteira melhora de forma sistemática [3].\n\n**O que muda na prática:** Escolha um processo para melhorar, aplique o ciclo completo com meta mensurável, documente o aprendizado e institua a revisão periódica (mensal) onde cada área apresenta o que planejou, fez, checou e aprendeu."
    ),
}
