#!/usr/bin/env python3
"""
Dados da Série MK3 — Funil de Atração, Conversão e Tráfego (20 livros)
Formato: slug -> (nome, titulo_obra, subtitulo, introducao, conclusao, capitulo1_explica)
Usado por dados_series_planejamento.py (merge) via gerar-livros-planejamento.py
"""

LIVROS_MK3 = {
    "MK3-01-arquitetura-de-trafego-pago-eficiente": (
        "Arquitetura de Tráfego Pago Eficiente (Meta, Google e TikTok)",
        "Arquitetura de Tráfego Pago Eficiente: Estruturando campanhas em Meta, Google e TikTok focadas estritamente em ROI e não em métricas de vaidade",
        "Estruturando campanhas focadas estritamente em ROI e não em métricas de vaidade",
        "O tráfego pago é a ferramenta mais rápida de gerar demanda — e a mais perigosa para o caixa quando mal arquitetada. Este livro ensina a estruturar campanhas em Meta, Google e TikTok do zero, com hierarquia de contas, orçamento por funil e decisões baseadas em ROI, não em impressões.",
        "Tráfego pago bem arquitetado é um investimento previsível: cada campanha tem objetivo, público e critério de corte definidos. Quem domina a arquitetura converte verba de mídia em receita mensurável — e quem ignora a estrutura queima caixa rápido.",
        "A arquitetura de tráfego pago organiza a conta de anúncios em camadas: campanhas (objetivo de negócio), conjuntos (público e leilão) e anúncios (criativos) [1]. Cada plataforma — Meta, Google e TikTok — tem lógica própria de leilão e otimização que precisa ser respeitada [2].\n\n**Por que importa?** Contas sem estrutura fazem as plataformas aprenderem errado: o algoritmo otimiza para o objetivo errado e a verba vira impressão. A arquitetura correta alinha cada campanha a um objetivo de negócio (venda, lead, tráfego qualificado) e define orçamento por estágio do funil [3].\n\n**O que muda na prática:** Monte a hierarquia de contas por funil (topo, meio, fundo), separe campanhas de aquisição e remarketing, e defina o ROAS mínimo como critério de manutenção de cada campanha."
    ),
    "MK3-02-gestao-de-campanhas-em-tempos-de-alta-de-custos": (
        "Gestão de Campanhas em Tempos de Alta de Custos de Mídia",
        "Gestão de Campanhas em Tempos de Alta de Custos de Mídia: Estratégias para proteger o orçamento diante do aumento de impostos e CPMs",
        "Estratégias para proteger o orçamento diante do aumento de impostos e CPMs",
        "CPM subindo, impostos sobre anúncios crescendo e margem apertando: o cenário de mídia paga está cada vez mais caro. Este livro ensina a proteger o orçamento em tempos de custos altos — otimizando estrutura, criativo e oferta em vez de simplesmente cortar verba.",
        "Alta de custos não é motivo para parar de anunciar — é motivo para anunciar melhor. Quem ajusta criativo, página e segmentação mantém o ROI mesmo com CPMs maiores, transformando o cenário adverso em vantagem competitiva contra quem recua.",
        "Quando o custo da mídia sobe, a resposta não é cortar verba: é aumentar a eficiência por clique. As alavancas são quatro: criativo (testar ângulos que reduzem o custo), página (elevar conversão para diluir o custo por venda), segmentação (qualificar o público para não pagar por clique frio) e oferta (aumentar ticket ou valor percebido) [1].\n\n**Por que importa?** Impostos e CPMs crescentes comprimem a margem de toda a operação digital ao mesmo tempo. Empresas que reagem ajustando estrutura e mensagem mantêm o CAC estável, enquanto as que cortam verba perdem participação e re-aprendizado de algoritmo [2].\n\n**O que muda na prática:** Em períodos de custo alto, revise o criativo vencedor, aumente a conversão da página e ajuste a oferta antes de reduzir verba — e documente o CAC antes/depois para medir o efeito real de cada alavanca [3]."
    ),
    "MK3-03-seo-tradicional-e-geo": (
        "Estratégias de SEO Tradicional e GEO (Generative Engine Optimization)",
        "Estratégias de SEO Tradicional e GEO: Otimizando o site para aparecer tanto nos buscadores clássicos quanto nas respostas de IA",
        "Otimizando o site para aparecer tanto nos buscadores clássicos quanto nas respostas de IA",
        "O Google ainda domina as buscas, mas as respostas de IA já decidem recomendações — e quem não otimiza para ambas desaparece dos dois lugares. Este livro une o SEO tradicional (técnica, conteúdo e autoridade) ao GEO, a otimização para motores generativos.",
        "Visibilidade não é mais jogo de um buscador: é presença em busca clássica E nas respostas das IAs. Quem domina as duas frentes captura o tráfego de hoje e a recomendação de amanhã, construindo autoridade que funciona em qualquer interface.",
        "O SEO tradicional otimiza o site para buscadores em três frentes: técnica (velocidade, indexação, estrutura), conteúdo (intenção de busca, autoridade, atualidade) e autoridade (links e sinais de confiança) [1]. O GEO (Generative Engine Optimization) adapta essa lógica para as respostas de IA: conteúdo estruturado, citações e respostas diretas que os modelos podem extrair e citar [2].\n\n**Por que importa?** As ferramentas de IA respondem com base em fontes que conseguem citar com clareza. Conteúdo bem estruturado, com dados verificáveis e linguagem direta, aparece nas respostas — enquanto páginas genéricas são ignoradas pelos dois ecossistemas [3].\n\n**O que muda na prática:** Audite o SEO técnico, produza conteúdo que responde perguntas de forma direta e estruturada, e monitore sua presença tanto no Google quanto nas respostas de IA para o seu nicho."
    ),
    "MK3-04-marketing-de-conteudo-baseado-em-autoridade": (
        "Marketing de Conteúdo Baseado em Autoridade",
        "Marketing de Conteúdo Baseado em Autoridade: Criando materiais profundos que constroem reputação e reduzem a resistência à compra",
        "Criando materiais profundos que constroem reputação e reduzem a resistência à compra",
        "Conteúdo raso atrai leitores que não compram; conteúdo profundo atrai compradores que confiam. Este livro ensina a construir autoridade por meio de materiais densos e úteis que posicionam a empresa como referência — e reduzem a resistência à compra na jornada inteira.",
        "Autoridade é o ativo que barateia todas as outras estratégias: com reputação técnica consolidada, o tráfego converte mais, o preço aguenta e o ciclo de venda encurta. Conteúdo profundo é o caminho mais durável para construí-la.",
        "O marketing de conteúdo baseado em autoridade produz materiais que demonstram domínio real do tema: guias profundos, estudos de caso, dados originais e posições claras [1]. A profundidade gera dois efeitos: os leitores qualificados se convencem da competência e o conteúdo atrai links e citações que reforçam a autoridade para os buscadores [2].\n\n**Por que importa?** Conteúdo superficial produz cliques baratos e nenhuma confiança. Conteúdo profundo reduz a resistência à compra porque responde as objeções antes de elas surgirem — o leitor chega à decisão já convencido [3].\n\n**O que muda na prática:** Escolha os temas em que a empresa é (ou quer ser) referência, produza materiais aprofundados sobre eles e distribua em um calendário consistente, medindo não só tráfego, mas tempo de leitura e conversão."
    ),
    "MK3-05-landing-pages-de-alta-conversao": (
        "Estruturação de Landing Pages de Alta Conversão (LP)",
        "Estruturação de Landing Pages de Alta Conversão: Elementos essenciais de design, copywriting e psicologia de consumo focados em conversão",
        "Elementos essenciais de design, copywriting e psicologia de consumo focados em conversão",
        "Todo o tráfego do mundo não vale nada se a página não converte. Este livro ensina a estruturar landing pages de alta conversão combinando design, copywriting e psicologia de consumo — do headline ao botão, do primeiro scroll ao formulário.",
        "Landing page é onde o investimento em tráfego vira resultado — ou vira desperdício. Uma LP bem estruturada eleva a conversão, reduz o custo por lead e transforma o mesmo volume de cliques em muito mais negócio.",
        "Uma landing page de alta conversão segue uma arquitetura de persuasão: headline que promete o benefício central, subheadline que amplia o contexto, proposta de valor clara, prova social, detalhes da oferta e um único chamado para ação [1]. O design conduz o olhar; o copy fala da dor e do desejo do visitante; a psicologia usa gatilhos de urgência e escassez sem apelar para o engano [2].\n\n**Por que importa?** A conversão é a alavanca que multiplica todo o investimento anterior: dobrar a conversão de 1% para 2% equivale a dobrar o tráfego sem pagar por ele. Cada elemento da página — título, imagem, prova, formulário — tem impacto medido no resultado final [3].\n\n**O que muda na prática:** Antes de lançar qualquer campanha, construa a LP com a arquitetura completa, teste o headline e o CTA, e meça a conversão por origem de tráfego para saber qual canal alimenta qual página."
    ),
    "MK3-06-copywriting-persuasivo-aplicado-ao-dia-a-dia": (
        "Copywriting Persuasivo Aplicado ao Dia a Dia",
        "Copywriting Persuasivo Aplicado ao Dia a Dia: Técnicas estruturadas de escrita para anúncios, e-mails e páginas de vendas",
        "Técnicas estruturadas de escrita para anúncios, e-mails e páginas de vendas",
        "A mesma oferta, escrita de um jeito, morre; escrita de outro, vende. Este livro ensina copywriting persuasivo aplicado ao dia a dia do marketing: técnicas estruturadas de escrita para anúncios, e-mails e páginas que transformam atenção em cliques e cliques em vendas.",
        "Copywriting é a habilidade de falar a língua da dor e do desejo do cliente. Quem domina as técnicas de escrita persuasiva produz materiais que convertem em qualquer canal — sem depender de sorte ou de talento inato.",
        "O copywriting persuasivo segue estruturas testadas: atenção (headline que para a leitura), interesse (contexto e relevância), desejo (benefícios e prova) e ação (chamado claro) [1]. As técnicas incluem escrever para uma persona específica, priorizar benefícios sobre características, usar gatilhos emocionais e revisar com edição cirúrgica [2].\n\n**Por que importa?** O texto é o ponto de contato entre o produto e a decisão de compra — em anúncios, e-mails e páginas. Copy fraco desperdiça tráfego pago, lista de e-mails e visitas; copy forte converte o mesmo tráfego por uma fração do custo [3].\n\n**O que muda na prática:** Reestruture os materiais atuais com a estrutura atenção-interesse-desejo-ação, escreva variantes para teste e meça a resposta de cada versão para acumular um banco de copy que funciona no seu mercado."
    ),
    "MK3-07-automacao-de-email-marketing-e-crm": (
        "Automação de E-mail Marketing e Relacionamento (CRM)",
        "Automação de E-mail Marketing e Relacionamento: Construindo fluxos automatizados de nutrição que educam e vendem no piloto automático",
        "Construindo fluxos automatizados de nutrição que educam e vendem no piloto automático",
        "A lista de e-mails é o ativo mais subvalorizado do marketing digital: alcança quem já confia, sem custo de mídia e com retorno alto. Este livro ensina a construir fluxos automatizados de nutrição no CRM que educam, relacionam e vendem no piloto automático.",
        "Automação de e-mail transforma a lista em máquina de vendas: cada novo lead entra em fluxos que o educam e conduzem à compra sem depender de operação manual. É o canal de melhor retorno por real investido do marketing digital.",
        "A automação de e-mail marketing combina três elementos: a captura (gerar leads por isca digital), o CRM (organizar contatos e gatilhos) e os fluxos (sequências automáticas de nutrição) [1]. Os fluxos principais são: boas-vindas, nutrição educacional, carrinho abandonado, reativação e pós-venda — cada um com objetivo e métrica própria [2].\n\n**Por que importa?** E-mail converte consistentemente melhor que mídia social porque chega na caixa de entrada de quem já demonstrou interesse. Automatizado, ele vende enquanto a equipe dorme, reduz o custo por venda e aumenta o valor do cliente ao longo do tempo [3].\n\n**O que muda na prática:** Configure a captura e o fluxo de boas-vindas primeiro, adicione a nutrição educacional com conteúdo do funil e meça aberturas, cliques e vendas de cada fluxo para otimizar continuamente."
    ),
    "MK3-08-estrategias-de-retargeting-inteligente": (
        "Estratégias de Retargeting Inteligente",
        "Estratégias de Retargeting Inteligente: Como reengajar visitantes que passearam pelo site ou loja física sem comprar",
        "Como reengajar visitantes que passearam pelo site ou loja física sem comprar",
        "A maioria dos visitantes não compra na primeira visita — e o retargeting existe exatamente para reencontrá-los no momento certo. Este livro ensina estratégias de retargeting inteligente: segmentação por comportamento, frequência adequada e mensagens que recuperam o interesse sem assediar.",
        "Retargeting é a arte de transformar interesse desperdiçado em venda: quem já visitou o site conhece a marca, só precisa do estímulo certo no momento certo. Bem executado, é um dos canais de melhor retorno e menor custo de aquisição.",
        "O retargeting inteligente segmenta os visitantes por comportamento: quem viu a home, quem viu um produto, quem abandonou o carrinho, quem já comprou [1]. Cada segmento recebe mensagem e oferta diferentes — informação para os de cima do funil, oferta e urgência para os de baixo [2].\n\n**Por que importa?** Visitante frio não compra por anúncio bonito; compra por sequência de exposição e prova. O retargeting por comportamento respeita o estágio da decisão, evita o desperdício de mostrar oferta a quem ainda está pesquisando e reduz o custo por venda recuperada [3].\n\n**O que muda na prática:** Instale o pixel e rastreie os eventos-chave, crie audiências por comportamento e estágio, monte criativos específicos por segmento e controle a frequência para maximizar retorno sem irritar o público."
    ),
    "MK3-09-marketing-de-influencia-e-criadores-locais": (
        "Marketing de Influência e Criadores de Conteúdo Locais",
        "Marketing de Influência e Criadores de Conteúdo Locais: Parcerias estratégicas com micro-influenciadores para gerar tráfego qualificado",
        "Parcerias estratégicas com micro-influenciadores para gerar tráfego qualificado",
        "Celebridades custam caro e convertem pouco; micro-influenciadores locais convertem mais e custam menos. Este livro ensina a montar parcerias estratégicas com criadores de conteúdo da sua região para gerar tráfego qualificado, confiança e vendas reais.",
        "O marketing de influência bem feito é uma troca: o criador entrega audiência e credibilidade, a marca entrega oferta e comissão. Com micro-influenciadores locais, o retorno é mais previsível, o custo é acessível e o público chega pré-qualificado pela afinidade geográfica.",
        "O marketing de influência seleciona criadores por três critérios: relevância (o público do criador é o público da marca), engajamento (interação real, não seguidores inflados) e autenticidade (o criador já conversa com o tema) [1]. Micro-influenciadores — entre 1 mil e 100 mil seguidores — oferecem o melhor equilíbrio entre alcance, custo e confiança [2].\n\n**Por que importa?** A recomendação de uma pessoa de confiança vale mais que o anúncio mais bem produzido: ela chega com credibilidade prévia e contexto. Em mercados locais, o criador regional fala a língua, conhece os pontos de dor e tem a audiência que a marca quer [3].\n\n**O que muda na prática:** Liste os criadores locais relevantes, analise engajamento e alinhamento, proponha parcerias com oferta clara e rastreie o retorno por cupom ou link exclusivo para medir o ROI de cada parceria."
    ),
    "MK3-10-gestao-de-leads-e-qualificacao-comercial": (
        "Gestão de Leads e Qualificação Comercial (MQL e SQL)",
        "Gestão de Leads e Qualificação Comercial: Garantindo que o time de vendas receba apenas contatos prontos para negociar",
        "Garantindo que o time de vendas receba apenas contatos prontos para negociar",
        "Marketing gera leads, vendas reclama da qualidade, e o funil trava na transição. Este livro ensina gestão de leads com qualificação comercial: critérios de MQL e SQL, pontuação de comportamento e o SLA de passagem de bastão que alinha as duas áreas.",
        "A qualificação de leads é a ponte entre marketing e vendas: quando cada área sabe exatamente o que recebe e o que entrega, o funil flui, a taxa de conversão sobe e o desperdício de esforço comercial acaba.",
        "A gestão de leads define dois patamares: MQL (Marketing Qualified Lead) — o contato que demonstrou interesse e se encaixa no perfil — e SQL (Sales Qualified Lead) — o contato pronto para negociar, com necessidade, orçamento e urgência [1]. A passagem de bastão exige critérios claros, definidos em conjunto, e um SLA de resposta que evite o lead esfriar [2].\n\n**Por que importa?** Vendedor que recebe lead frio desiste do processo; lead quente que espera demais esfria. Com MQL/SQL bem definidos, o comercial trabalha só o que vale a pena e o marketing passa a ser cobrado por qualidade, não por volume [3].\n\n**O que muda na prática:** Defina com vendas os critérios de MQL e SQL, configure a pontuação de comportamento no CRM e estabeleça o SLA de primeiro contato — depois monitore a taxa de conversão MQL→SQL→venda como métrica conjunta."
    ),
    "MK3-11-programas-de-indicacao-referral": (
        "Criação e Gestão de Programas de Indicação (Referral)",
        "Criação e Gestão de Programas de Indicação: Transformando clientes atuais em canais ativos de aquisição de novos compradores",
        "Transformando clientes atuais em canais ativos de aquisição de novos compradores",
        "Seu melhor vendedor já comprou de você. O programa de indicação transforma clientes satisfeitos em canal ativo de aquisição — com incentivo, rastreio e escala. Este livro ensina a criar, lançar e gerir um programa de referral que gera clientes novos por confiança, não por anúncio.",
        "Indicação é o canal de menor custo e maior conversão: o indicado chega pré-convencido e o indicador já é fã da marca. Um programa bem estruturado transforma essa boa vontade em crescimento mensurável e recorrente.",
        "Um programa de indicação desenha o incentivo em duas pontas: o indicador ganha (crédito, desconto, benefício) e o indicado também — o que reduz a barreira de aceitar o convite [1]. A operação exige rastreio confiável (como saber quem indicou quem), comunicação simples e regras claras de elegibilidade e pagamento [2].\n\n**Por que importa?** O custo de aquisição por indicação é uma fração do custo de mídia paga, e o indicado tem maior LTV porque chega com confiança e contexto. Além disso, clientes que indicam se tornam defensores mais engajados da marca [3].\n\n**O que muda na prática:** Escolha o incentivo adequado à margem, defina o mecanismo de rastreio (link ou cupom), comunique o programa no pós-venda e meça a taxa de conversão dos indicados para validar o retorno do investimento."
    ),
    "MK3-12-omnicanalidade-no-varejo-e-b2b": (
        "Estratégias de Omnicanalidade no Varejo e B2B",
        "Estratégias de Omnicanalidade no Varejo e B2B: Integrando o carrinho abandonado do site com o atendimento via WhatsApp da loja física",
        "Integrando o carrinho abandonado do site com o atendimento via WhatsApp da loja física",
        "O cliente não separa canais: pesquisa no site, visita a loja, fecha no WhatsApp. Este livro ensina estratégias de omnicanalidade para varejo e B2B — integrando carrinho abandonado, atendimento físico, WhatsApp e e-commerce em uma única jornada sem fricção.",
        "Omnicanalidade é tratar o cliente como único, não o canal: dados e histórico compartilhados, atendimento contínuo entre físico e digital e ofertas coerentes em qualquer ponto de contato. Quem integra os canais retém mais e vende mais.",
        "A omnicanalidade integra canais em três camadas: dados (uma visão única do cliente em todos os sistemas), operação (estoque, entrega e atendimento conectados) e comunicação (o carrinho abandonado no site é retomado no WhatsApp, a consulta na loja é acompanhada pelo e-commerce) [1]. No varejo, a integração físico-digital é o diferencial contra o e-commerce puro; no B2B, o WhatsApp e o relacionamento pessoal complementam a venda online [2].\n\n**Por que importa?** Cada ruptura entre canais é uma venda ou um cliente perdido: quem abandona o carrinho no site e recebe o lembrete no WhatsApp fecha; quem precisa repetir a história para cada atendente desiste. A experiência integrada aumenta a conversão e o valor do cliente [3].\n\n**O que muda na prática:** Conecte o CRM ao e-commerce e ao WhatsApp, configure o fluxo de carrinho abandonado com recuperação via mensageria e treine a operação para atender o cliente com contexto único em qualquer canal."
    ),
    "MK3-13-otimizacao-de-conversao-cro": (
        "Otimização de Conversão (CRO) em E-commerce e Sites",
        "Otimização de Conversão (CRO) em E-commerce e Sites: Removendo atritos de navegação, checkout e formulários para elevar taxas de venda",
        "Removendo atritos de navegação, checkout e formulários para elevar taxas de venda",
        "Dobrar o tráfego custa caro; dobrar a conversão custa método. Este livro ensina otimização de conversão (CRO) para e-commerce e sites: como identificar atritos em navegação, checkout e formulários, testar hipóteses e elevar a taxa de venda com o mesmo tráfego.",
        "CRO é a alavanca de maior retorno do marketing digital: melhorar a conversão de 1% para 2% equivale a dobrar a receita sem aumentar o investimento em mídia. É um processo contínuo de diagnóstico, hipótese, teste e implementação.",
        "O CRO segue um ciclo: diagnóstico (dados de análise e mapas de calor revelam onde o usuário desiste), hipótese (por que ele desiste), teste (A/B testa a mudança) e implementação (o vencedor entra em produção) [1]. Os atritos típicos são: navegação confusa, checkout longo, formulários extensos, falta de prova social e lentidão de carregamento [2].\n\n**Por que importa?** Tráfego é caro; conversão é barata. Cada ponto percentual de conversão a mais multiplica o retorno de todo o investimento em aquisição — e o aprendizado dos testes acumula conhecimento sobre o cliente que vale para todas as campanhas [3].\n\n**O que muda na prática:** Instale análise e mapa de calor, liste os atritos principais do funil, priorize as correções de maior impacto e monte uma rotina de testes A/B contínua com critério estatístico claro."
    ),
    "MK3-14-gestao-de-reputacao-online": (
        "Gestão de Reputação Online e Avaliações (Google Meu Negócio)",
        "Gestão de Reputação Online e Avaliações: Como blindar e alavancar a imagem da empresa através de reviews de clientes",
        "Como blindar e alavancar a imagem da empresa através de reviews de clientes",
        "Antes de comprar, o cliente pesquisa: avaliações no Google, comentários nas redes, reputação geral. Este livro ensina a gerir a reputação online — respondendo avaliações, incentivando reviews positivos e usando o Google Meu Negócio para blindar e alavancar a imagem da empresa.",
        "Reputação online é o ativo intangível que decide a primeira impressão: empresas bem avaliadas convertem mais, cobram mais e resistem melhor a crises. A gestão ativa de avaliações transforma feedback em vantagem competitiva.",
        "A gestão de reputação online tem três frentes: monitoramento (acompanhar avaliações e menções em todas as plataformas), resposta (responder positivas e negativas com velocidade e empatia) e geração (incentivar clientes satisfeitos a avaliar) [1]. O Google Meu Negócio é a vitrine local mais importante: perfil completo, fotos, respostas e avaliações influenciam diretamente a decisão de compra e o SEO local [2].\n\n**Por que importa?** Avaliação negativa sem resposta espanta clientes; avaliação respondida com respeito impressiona até quem lê depois. A reputação gerida ativamente reduz o custo de aquisição — o cliente chega já confiante, em vez de chegar desconfiado [3].\n\n**O que muda na prática:** Reivindique e complete o perfil do Google Meu Negócio, crie um processo de resposta a avaliações em 24h, incentive reviews no pós-venda e monitore as menções da marca nas principais plataformas."
    ),
    "MK3-15-estrategias-de-video-marketing": (
        "Estratégias de Vídeo Marketing de Curta e Longa Duração",
        "Estratégias de Vídeo Marketing de Curta e Longa Duração: Produzindo conteúdos em vídeo que geram conexão rápida e desejo de compra",
        "Produzindo conteúdos em vídeo que geram conexão rápida e desejo de compra",
        "O vídeo domina a atenção digital — e cada formato tem função própria: o curto gera alcance, o longo constrói confiança. Este livro ensina estratégias de vídeo marketing de curta e longa duração, com produção enxuta, distribuição inteligente e métricas por objetivo.",
        "Vídeo é a linguagem da conexão: o curto pega a atenção no scroll, o longo aprofunda a relação e conduz à compra. Uma estratégia que combina os dois formatos multiplica o alcance e a conversão com o mesmo time e o mesmo orçamento.",
        "O vídeo marketing combina formatos por objetivo: curta duração (Reels, Shorts, TikTok) para alcance, descoberta e autoridade rápida; longa duração (YouTube, lives, vídeos de venda) para educação, confiança e conversão [1]. A produção enxuta prioriza o conteúdo sobre a estética: roteiro claro, iluminação básica e edição simples entregam resultado antes de equipamento caro [2].\n\n**Por que importa?** Os algoritmos das plataformas favorecem vídeo, e o público confia mais em quem mostra a cara e explica do que em texto anônimo. O vídeo curto alimenta o topo do funil; o longo fecha o fundo — juntos, reduzem o custo de aquisição e aumentam a conversão [3].\n\n**O que muda na prática:** Defina os pilares de conteúdo em vídeo, produza curtas com gancho nos primeiros segundos, use o YouTube como canal de profundidade e reutilize cada material em múltiplos formatos e plataformas."
    ),
    "MK3-16-campanhas-sazonais-de-queima-de-estoque": (
        "Campanhas Sazonais de Queima de Estoque",
        "Campanhas Sazonais de Queima de Estoque: Planejando datas específicas (Black Friday, aniversários da marca) com foco em margem e caixa",
        "Planejando datas específicas (Black Friday, aniversários da marca) com foco em margem e caixa",
        "Queima de estoque não é liquidação desesperada: é operação planejada de margem e caixa. Este livro ensina a montar campanhas sazonais — Black Friday, aniversário da marca, virada de coleção — com objetivos claros, seleção de produtos e comunicação que esgota estoque sem destruir a margem.",
        "A campanha sazonal bem planejada cumpre dois objetivos: girar estoque e gerar caixa — sem sacrificar o posicionamento. Com seleção de produtos, precificação e comunicação definidas de antemão, a data vira lucro previsível em vez de corrida ao desconto.",
        "A queima de estoque eficiente começa pela seleção: separar o que precisa girar (por vencimento, sazonalidade ou liquidez) do que sustenta margem [1]. A precificação define o desconto máximo por produto, preservando o ponto de equilíbrio; a comunicação segmenta a oferta por público — cliente antigo recebe condição melhor que o novo [2].\n\n**Por que importa?** Estoque parado tem custo financeiro e físico: dinheiro preso, depreciação e espaço. A queima programada transforma esse passivo em caixa, e a campanha sazonal bem executada ainda conquista clientes novos que podem se tornar recorrentes [3].\n\n**O que muda na prática:** Monte o calendário de datas do negócio, selecione produtos por objetivo (girar vs. margem), defina descontos máximos por produto e prepare a comunicação segmentada com antecedência de pelo menos 30 dias."
    ),
    "MK3-17-uso-de-ferramentas-de-mensageria-whatsapp-business-api": (
        "Uso de Ferramentas de Mensageria (WhatsApp Business API)",
        "Uso de Ferramentas de Mensageria: Automatizando o atendimento inicial sem perder o toque humanizado",
        "Automatizando o atendimento inicial sem perder o toque humanizado",
        "O WhatsApp é o canal de relacionamento número um do Brasil — e a automação pode matar ou potencializar essa relação. Este livro ensina o uso de ferramentas de mensageria, com a WhatsApp Business API, para automatizar o atendimento inicial sem perder o toque humanizado que converte.",
        "Mensageria bem estruturada responde na hora, qualifica o cliente e humaniza o atendimento — tudo em um só canal. Automatizar o início da conversa e escalar para o humano no momento certo é o equilíbrio que transforma WhatsApp em máquina de vendas.",
        "A WhatsApp Business API permite automação estruturada do atendimento: mensagens de boas-vindas, respostas a perguntas frequentes, catálogo de produtos, notificações de pedido e roteamento para atendente humano [1]. O desenho do fluxo define o que a máquina resolve (duvidas simples, agendamento, status) e o que sobe para o humano (negociação, objeções, pós-venda sensível) [2].\n\n**Por que importa?** O cliente espera resposta imediata — e a automação entrega o primeiro retorno em segundos, 24 horas por dia. Mas automação sem saída para o humano frustra: o toque humanizado no momento certo é o que converte e fideliza [3].\n\n**O que muda na prática:** Configure o catálogo e as respostas automáticas iniciais, defina os fluxos que a máquina resolve, crie o roteamento para atendimento humano e monitore o tempo de resposta e a satisfação do atendimento automatizado."
    ),
    "MK3-18-eventos-e-experiencias-presenciais": (
        "Planejamento de Eventos e Experiências Presenciais (Live Marketing)",
        "Planejamento de Eventos e Experiências Presenciais: Estruturando ações físicas que geram buzz digital e conversão direta",
        "Estruturando ações físicas que geram buzz digital e conversão direta",
        "O presencial voltou — e, integrado ao digital, virou a ferramenta mais forte de relacionamento e venda. Este livro ensina a planejar eventos e experiências presenciais de live marketing: objetivos claros, ativação memorável, captação de dados e amplificação digital do que acontece no físico.",
        "Evento bem planejado gera três resultados ao mesmo tempo: venda direta, relacionamento profundo e conteúdo digital que se espalha. A experiência presencial cria memória emocional que nenhum anúncio reproduz — e o digital amplifica o alcance do que aconteceu.",
        "O planejamento de eventos começa pelo objetivo: lançar, vender, relacionar ou coletar dados — cada objetivo define o desenho da ativação [1]. A experiência deve ser memorável (algo que o participante queira contar), mensurável (captação de contato, venda no local ou códigos de rastreio) e amplificável (momentos pensados para virar conteúdo digital) [2].\n\n**Por que importa?** O presencial gera confiança e emoção que o digital não alcança, e o digital multiplica o alcance do presencial: uma ativação boa vira centenas de posts, stories e reels espontâneos. Juntas, as duas frentes reduzem o custo por cliente conquistado [3].\n\n**O que muda na prática:** Defina o objetivo do evento, desenhe a experiência com momento de captação e foto/vídeo, prepare a amplificação digital antes do dia e meça o resultado por vendas, contatos captados e alcance do conteúdo gerado."
    ),
    "MK3-19-comunidades-de-marca-engajadas": (
        "Construção de Comunidades de Marca Engajadas",
        "Construção de Comunidades de Marca Engajadas: Criando ecossistemas próprios onde os clientes fiéis debatem, compram e defendem a marca",
        "Criando ecossistemas próprios onde os clientes fiéis debatem, compram e defendem a marca",
        "A marca que tem comunidade não compete por atenção: tem audiência própria que defende, compra e recruta. Este livro ensina a construir e gerir comunidades de marca engajadas — grupos, clubes e ecossistemas onde os clientes fiéis debatem, compram e defendem a empresa.",
        "Comunidade é o ativo de marketing mais difícil de copiar: ninguém replica a relação entre a marca e seus membros. Uma comunidade engajada reduz custo de aquisição, aumenta retenção e gera feedback constante que orienta todas as outras estratégias.",
        "Uma comunidade de marca tem estrutura clara: propósito (por que ela existe além da venda), regras de convivência (o que é bem-vindo), rituais (conteúdo, eventos e tradições regulares) e benefícios (acesso, vantagens e reconhecimento para os membros) [1]. A gestão equilibra dar valor antes de pedir: a comunidade prospera quando a marca entrega conteúdo, atenção e benefícios reais, não quando só usa o grupo para anunciar [2].\n\n**Por que importa?** Clientes de comunidade têm maior LTV (compram mais e por mais tempo), indicam ativamente (reduzindo CAC) e geram feedback em tempo real que orienta produto, conteúdo e campanhas — uma vantagem que anúncio nenhum compra [3].\n\n**O que muda na prática:** Escolha a plataforma (grupo, comunidade ou clube), defina o propósito e os benefícios para membros, crie rituais de engajamento semanais e meça não só participação, mas o impacto da comunidade em retenção e indicações."
    ),
    "MK3-20-metricas-de-vaidade-vs-metricas-de-negocio": (
        "Análise de Métricas de Vaidade vs. Métricas de Negócio",
        "Análise de Métricas de Vaidade vs. Métricas de Negócio: Separando curtidas e impressões de receita líquida e lucro operacional",
        "Separando curtidas e impressões de receita líquida e lucro operacional",
        "Curtidas não pagam contas — mas muitos gestores ainda confundem vaidade com resultado. Este livro ensina a separar métricas de vaidade (impressões, curtidas, alcance) de métricas de negócio (receita, margem, lucro operacional) e a montar o painel que realmente orienta decisões.",
        "A métrica certa muda a decisão: quem olha impressões investe em alcance; quem olha lucro investe em conversão e retenção. Dominar a distinção entre vaidade e negócio é o primeiro passo para um marketing que responde pelo caixa.",
        "Métricas de vaidade medem exposição sem conexão direta com resultado financeiro: impressões, alcance, curtidas, seguidores, visualizações [1]. Métricas de negócio medem valor gerado: receita, margem de contribuição, CAC, LTV, conversão e lucro operacional [2]. A regra de ouro: toda métrica de vaidade deve rastrear até uma métrica de negócio — se não rastreia, ela informa pouco.\n\n**Por que importa?** Campanhas que otimizam vaidade inflam o ego e esvaziam o caixa: milhões de impressões sem venda são desperdício de verba e tempo. Decisões baseadas em métricas de negócio protegem a margem e revelam o que realmente cresce a empresa [3].\n\n**O que muda na prática:** Liste as métricas que o time acompanha hoje, classifique cada uma como vaidade ou negócio, remova do painel o que não rastreia resultado financeiro e adote receita, margem, CAC e LTV como métricas-mestre."
    ),
}
